### ISSUE TITLE
Mapping to NI Traktor Kontrol S3

### ISSUE THREAD

**Issue by GLRhone** [mixxxdj/mixxx#11255] opened 2023-02-08 13:59 UTC
### Bug Description

I recently bought the NI Traktor Kontrol S3 controller with the intention of using it with Mixxx.  All indications suggested the mapping for this hardware was done around end 2020, and so i went ahead and bought the gear. However, when i connect the controller and select it in the Mixxx preferences i receive an error message in a pop-up window (details pasted below).

Thanks in advance for any help that can be provided!

Regards, GLRhone

**Pop-up window:**

'The mapping for your controller 'Traktor Kontrol S3 CB96_3' is not working properly. The script code needs to be fixed. Functionality provided by this mapping will be disabled until resolved'

The details of the error in the sub-window are as follows:

Uncaught exception at line 1912 in file C:/Program Files/Mixxx/controllers/Traktor-Kontrol-S3-hid-scripts.js.

Exception:

TypeError: Result of expression 'engine.makeUnbufferedConnection' [undefined] is not a function.

Backtrace:

<anonymous>() at C:/Program Files/Mixxx/controllers/Traktor-Kontrol-S3-hid-scripts.js:1912

<anonymous>(_id = 'Traktor Kontrol S3 CB96_3', false) at C:/Program Files/Mixxx/controllers/Traktor-Kontrol-S3-hid-scripts.js:2261

<global>() at -1

### Version

2.3.2

### OS

Windows 10 Professional

**Comment by Swiftb0y** [comment] 2023-02-08 14:17
Something seems wrong with your mixxx setup. You are using a mapping from the upcoming version 2.4 with version 2.3.2 (which is also outdated btw, please use 2.3.3). It could be also that we messed up something between the different versions but I doubt that. Either use the newer 2.4 version of mixxx or restore the mapping by deleting the folder containing the mappings (`C:\Program Files\Mixxx\controllers\`) and reinstall Mixxx. 

Cc @JoergAtGithub

**Comment by JoergAtGithub** [comment] 2023-02-08 18:00
Duplicate of https://github.com/mixxxdj/mixxx/issues/10660
This is a mapping bug in Mixxx 2.3.2, which is fixed in the actual Mixxx release 2.3.3. Please update your Mixxx installation!

**Closed by JoergAtGithub** 2023-02-08 18:00 UTC
Labels: bug

**Comment by GLRhone** [comment] 2023-02-09 11:02
Thanks for the info. Have upgraded my installation to 2.3.3 and will try the controller shortly. Many thanks for the guidance!!
