### ISSUE TITLE
Beatjumping  a Loop looses sync

### ISSUE THREAD

**Issue by obsoleszenz** [mixxxdj/mixxx#11381] opened 2023-03-16 14:56 UTC
### Bug Description

Beatjumping / moving a loop often looses sync with other decks, sometimes being just slightly off sometimes more noticable. It also seems to increase the more often one jumps. Interestingly this doesn't happen if a loop is not enabled.
Also it doesn't happen if the loop just moves inside it's own range (moving a 8beat loop one beat back wont cause a problem). But it happens if one moves a 4 beat loop 8beat back/forth.

### Reproduce

1. Load two tracks with 4onthefloor beats to make things easy
2. Enable quantization on both
3. set loops on both decks
4. beatmatch
5. let one of the tracks jump back with a jump size > the activated loop size
6. they are out of sync, if not try again

### Version

2.3.4

### OS

Linux

**Comment by obsoleszenz** [comment] 2023-03-16 15:54
Yes quantize is enabled. What is a non const beat grid? In case it's about variable tempo, no tempo is constant.

**Comment by MarcPlace** [comment] 2023-03-25 04:13
I've noticed a similar issue when I try to decrease beats on a running loop e.g. from 8 to 4 beats.
For example deck 1 and 2 are completely in sync (let's say both running on 120 BPM, beat is matched). Now I'm setting a loop on deck 1 with 8 beats while deck 2 is still playing => both are still in perfect sync. Now I decrease the loop on deck 1 from 8 to 4 beats => deck 1 now gets out of sync of deck 2. The more I'm decreasing beats, the more it drifts away (e.g. when I'm setting a loop with 32 beats, and then I'm decreasing it to 16 => 8 => 4 while running).
Oddly enough, increasing a running loop seems to work fine, haven't seen any problems with it so far.
I'm using 2.4 alpha (recent commit 0e7601c0f7c30a5f497e98c422e454a3a6c6eef2) on Linux.

**Comment by ronso0** [comment] 2023-03-26 16:34
Do you halve the loop while you're in the first halve of it? Like, no potential conflict of playposition and loop_out marker?

**Comment by MarcPlace** [comment] 2023-03-26 18:30
Oh, good question... wasn't aware of. So I did some further investigations and yes, it seems that it happens (only?) in the second half of the loop e.g. if the loop decreases from 8 beats width to 4 beats while it plays already the 5th or 6th beat within the loop.
But I'm pretty sure I did this also already quite often in previous versions with no problems at all. Unfortunately I don't know if my issue has an impact or something to do with @obsoleszenz failure while he was moving a loop forth and back. But yes, maybe it could be.

**Comment by ronso0** [comment] 2023-03-26 21:19
>  yes, it seems that it happens (only?) in the second half of the loop e.g. if the loop decreases from 8 beats width to 4 beats while it plays already the 5th or 6th beat within the loop.

Hmkay, the code to calculate the new position is here, but it looks like there haven't been relevant changes for years, so the source must be somewhere else IMO.
https://github.com/mixxxdj/mixxx/blob/9db1ac195f4a14f90fee5e2b09a68b4c3b7f6c1f/src/engine/controls/loopingcontrol.cpp#L1280-L1292

Can you confirm the shift is not a result of the engine being overstrained, i.e. no buffer underruns occur? (see buffer underrun counter at the bottom of Pref >-Sound Hardware).

Could you please verify this shift was introduced by 2.3.4, like test again with 2.3.3 (or earlier version if you find 2.3.3 is also affected).

**Comment by obsoleszenz** [comment] 2023-03-27 02:01
> Can you confirm the shift is not a result of the engine being overstrained, i.e. no buffer underruns occur? (see buffer underrun counter at the bottom of Pref >-Sound Hardware).

Seems not to be the case, counter did not increase

> Could you please verify this shift was introduced by 2.3.4, like test again with 2.3.3 (or earlier version if you find 2.3.3 is also affected).

As there are no appimages i can't test the 2.3.3 again without compiling from source :/

But it's really easy to test:
1. Load two tracks with 4onthefloor beats to make things easy
2. Enable quantization on both
3. set loops on both decks
4. beatmatch
5. let one of the tracks jump back with a jump size > the the activated loop size

**Comment by MarcPlace** [comment] 2023-03-27 19:12
> Can you confirm the shift is not a result of the engine being overstrained, i.e. no buffer underruns occur? (see buffer underrun counter at the bottom of Pref >-Sound Hardware).

Yes, no underruns here, the counter still shows 0 when this issue occurs.

> Could you please verify this shift was introduced by 2.3.4, like test again with 2.3.3 (or earlier version if you find 2.3.3 is also affected).

Went back to 2.3.3 release version just to be sure and yes, it already happens in this version too. Very odd, never noticed it before. Btw I use the buttons on my Denon MC7000 controller to change the width of the loop. But I've counter checked this using the loop buttons on the skin... it also happens there.
And after all I come to this conclusion that it really happens only in the second half of the loop. If I decrease the loop in the first half (e.g. set an 8 beats loop, and reducing it to 4 beats within the first 4 beats) it seems to work quite well.
HTH

**Comment by obsoleszenz** [comment] 2023-03-28 13:32
> > yes, it seems that it happens (only?) in the second half of the loop e.g. if the loop decreases from 8 beats width to 4 beats while it plays already the 5th or 6th beat within the loop.
> 
> Hmkay, the code to calculate the new position is here, but it looks like there haven't been relevant changes for years, so the source must be somewhere else IMO.
> 
> https://github.com/mixxxdj/mixxx/blob/9db1ac195f4a14f90fee5e2b09a68b4c3b7f6c1f/src/engine/controls/loopingcontrol.cpp#L1280-L1292
> 
> Can you confirm the shift is not a result of the engine being overstrained, i.e. no buffer underruns occur? (see buffer underrun counter at the bottom of Pref >-Sound Hardware).
> 
> Could you please verify this shift was introduced by 2.3.4, like test again with 2.3.3 (or earlier version if you find 2.3.3 is also affected).

I'm currently debugging this and looks like the pointed out code is not the problem.

**Comment by ronso0** [comment] 2023-03-28 19:41
> * Load two tracks with 4onthefloor beats to make things easy
> * Enable quantization on both
>* set loops on both decks
> * beatmatch
> * let one of the tracks jump back with a jump size > the activated loop size
> * they are out of sync

I can not reproduce the issue with Mixxx 2.3.4. I did
* **deck 1**: load a track with a perfectly set beatgrid (const tempo) to deck 1
* **deck 1 & 2**: enable quantize, center pitch fader on both decks
* **deck 1**: hit play, set a 8-beat loop, 
* drag the track over to the other **deck 2** = deck clone = both decks play perfectly in sync (with loops: forever)
* on one deck halve loop, move it, double it, move it (beatjump size > loop size), no matter what I do ...
* beatgrids on deck 1 & 2 are always in sync

@obsoleszenz Could it be you confuse 'quantize' with beatsync? Like, the tempo of tracks is not the same and they are not synced 100% and jumping around makes this more obvious over time?

FWIW I could also not reproduce it with two different tracks (130.2 vs 160) when using Sync lock. No beat grid shift noticable.

**Comment by obsoleszenz** [comment] 2023-03-29 07:36
> > * Load two tracks with 4onthefloor beats to make things easy
> > * Enable quantization on both
> > * set loops on both decks
> > * beatmatch
> > * let one of the tracks jump back with a jump size > the activated loop size
> > * they are out of sync
> 
> I can not reproduce the issue with Mixxx 2.3.4. I did
> 
>     * **deck 1**: load a track with a perfectly set beatgrid (const tempo) to deck 1
> 
>     * **deck 1 & 2**: enable quantize, center pitch fader on both decks
> 
>     * **deck 1**: hit play, set a 8-beat loop,
> 
>     * drag the track over to the other **deck 2** = deck clone = both decks play perfectly in sync (with loops: forever)
> 
>     * on one deck halve loop, move it, double it, move it (beatjump size > loop size), no matter what I do ...
> 
>     * beatgrids on deck 1 & 2 are always in sync
> 
> 
> @obsoleszenz Could it be you confuse 'quantize' with beatsync? Like, the tempo of tracks is not the same and they are not synced 100% and jumping around makes this more obvious over time?
> 
> FWIW I could also not reproduce it with two different tracks (130.2 vs 160) when using Sync lock. No beat grid shift noticable.

I figured out it's easier to reproduce with quantize being disabled, as quantize will resync the tracks by pitching up/down one track, so it's slightly off but mixxx will try to fix it again.

A better way to reproduce it is this:
- load  two track with a perfectly set beatgrid (const tempo) to deck 1 & 2
- play them and beatmatch
- disable quantization on both
- now jump 16 beat backwards on deck1
- everything should be still beatmatched
- now jump 16 beat forward on deck1
- everything should be still beatmatched
- now set a 4 beat loop on deck1 
- now jump 16 beat backward on deck1
- not beatmatched anymore

**Comment by ronso0** [comment] 2023-03-29 11:25
Still can't reproduce if I use deck cloning after starting deck1. No matter how I resize or move the loop, beatgrids are aligned.

**Comment by obsoleszenz** [comment] 2023-04-05 16:22
> Still can't reproduce if I use deck cloning after starting deck1. No matter how I resize or move the loop, beatgrids are aligned.
> 
> Can you reproduce with a cloned deck? Can you reproduce with diff. tracks after you hit Sync to have parallel beatgrids?

Yup also happens with a cloned deck. But might be more noticable without syncing.

**Comment by obsoleszenz** [comment] 2023-04-05 16:35
I recorded a small video showing the problem:
https://transfer.sh/5QYzcN/output.webm

**Comment by obsoleszenz** [comment] 2023-04-05 16:50
Here a longer video with syncing & quantization turned one, one can hear that mixxx somehow fixes the syncing but directly after the jump it's out of sync:
https://transfer.sh/Wx2uzI/output.mkv

**Comment by obsoleszenz** [comment] 2023-04-05 21:43
@ronso0 can you make sure that you have key sync disabled? It doesn't happen for me when key sync is enabled (my current theory is that the bug is somewhere in the enginebufferscale?)

**Comment by MarcPlace** [comment] 2023-04-05 23:56
I have observed the following when I tried to reproduce @obsoleszenz issue and mine (these are two different cases, but I think the source of our issues could be the same):
I've cloned the same track from deck 1 to deck 2 while playing, setting loops on both decks, and then beatjump a loop on one deck (doesn't matter which one). Everything is in sync, I can jump the loop around with no issues at all.
Now take a 125 BPM track and **change pitch** to let's say 126 BPM, and repeat above steps once again. That was the point where I could also reproduce @obsoleszenz issue.
Maybe I can manage to produce a quick video the next days to show my issue also.

**Comment by ronso0** [comment] 2023-04-06 14:57
To summarize:
* with rate slider centered seeks are perfect
* with quantize enabled seeks are perfect
* amount of rate offset doesn't matter as long as it's > 0
* with rate offset, both forward and backward loopmoves cause a shift 
* seek offset depends on the buffer size: the bigger the buffer, the bigger the offset

Maybe the issue is somewhere in https://github.com/mixxxdj/mixxx/blob/e4b8463eedbc5177fde78871e3c29d4342d0a78e/src/engine/controls/loopingcontrol.cpp#L1264 or https://github.com/mixxxdj/mixxx/blob/e4b8463eedbc5177fde78871e3c29d4342d0a78e/src/engine/enginebuffer.cpp#L724

**PS** contrary to my first test I can now reproduce it even with smaller jumps and with rate centered :man_shrugging:

**Comment by ronso0** [comment] 2023-04-08 22:49
btw https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/LoopingControl.3A.3AnextTrigger.28.29

Did some debugging, and `LoopingControl::seekInsideAdjustedLoop` called by `LoopingControl::nextTrigger`, and `EngineBuffer::processTrackLocked` themselves seem okay.
The offset we see might be introduced by [`ReadAheadManager::getNextSamples`](https://github.com/mixxxdj/mixxx/blob/425ad1e47ae9d5962a83633ba6e2663caf1d4a6f/src/engine/readaheadmanager.cpp#L38) (see `reachedTrigger` and `overshoot`).

**Comment by ronso0** [comment] 2023-05-16 13:06
Removing the flushing code path touched in #11152 fixes the loopmove offset :tada: 
Though, I'm not familiar with the scale, there's probably a scenario where flushing is required to avoid other failures/offsets.

**Comment by ronso0** [comment] 2023-06-06 20:22
Fixed by #11152

**Closed by ronso0** 2023-06-06 20:22 UTC
Labels: bug, confirmed, looping, beatgrid
