### ISSUE TITLE
Last item of the playlist grid hidden under scrollbar when columns exceed screen size

### ISSUE THREAD

**Issue by mkukawski** [mixxxdj/mixxx#11632] opened 2023-06-06 16:25 UTC
### Bug Description

When the scrollbar enables it should not overlay the last playlist item.

See the example screenshot.
Expected: Item 31 shown above the scrollbar
Actual: Scrollbar covers item in line 31
<img width="1436" alt="Screenshot 2023-06-06 at 17 22 10" src="https://github.com/mixxxdj/mixxx/assets/26073015/d95a4d7a-af14-406c-969a-6f0170b84e7c">

### Version

2.4.0

### OS

MacOS

**Comment by mkukawski** [comment] 2023-06-06 16:54
I think its not the space problem as we are in scrolling mode, its just the
grid should not overlap the scrollbar but be touching side of it.

**Comment by ronso0** [comment] 2023-06-06 19:45
This is a duplicate of #9495

**Closed by ronso0** 2023-06-06 19:45 UTC
Labels: bug
