### ISSUE TITLE
GCC 13: EQ/Filters/Waveforms broken

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11483] opened 2023-04-16 10:51 UTC
### Bug Description

- EQs don't seem to work properly and the high EQ causes weird overdrive noise when turning down (see also #11409)
- Waveforms look strange:

![image](https://user-images.githubusercontent.com/1474154/232239271-06eb1c69-d769-4529-9145-ce769cc8cbf1.png)

Tested with both the old and new fidlib code from 2.3 (#11475 + #11478). Probably undefined behavior.

Built with `-DOPTIMIZE=native` and `-DOPTIMIZE=portable` on Intel Skylake.

All tests pass.

### Updates

- Independent of the optimization settings
- Clang 16.0 with `-DOPTIMIZE=native` works (but causes another issue: #11484)

**Comment by daschuer** [comment] 2023-04-16 18:01
Did you post two issues in GitHub issue? This is hard to handle. Can you spit them? 
It this the EQ part a duplicate of https://github.com/mixxxdj/mixxx/issues/11409

**Comment by uklotzde** [comment] 2023-04-16 18:31
Probably a duplicate of #11409, which only mentions the audible errors. But the errors are also visible in waveforms. Same root cause.

The preconditions for reproducing it are described here, i.e. GCC 13 + `-DOPTIMIZE=native`.

**Comment by daschuer** [comment] 2023-04-16 19:23
Ah OK, so the visual issue in the waveforms happens due to the broken filter. 

In #11409 the command line of fildlib.c has some extra flags. It would be nice to see the original compiler invocation in your case as well, to check if there are any differences. 

Even though @hapst3r has compiled with OPTIMIZE=portable he experienced the filter issues. So there must be a subtle difference.

**Comment by uklotzde** [comment] 2023-04-16 20:35
/usr/lib64/ccache/cc -DMIXXX_USE_QOPENGL -DT_LINUX -g -fvisibility=hidden -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=native -o CMakeFiles/fidlib.dir/lib/fidlib/fidlib.c.o -c /home/uk/volumes/Build/cpp/mixxx/lib/fidlib/fidlib.c

**Comment by uklotzde** [comment] 2023-04-16 20:42
`-DOPTIMIZE=portable` (works):
/usr/lib64/ccache/cc -DMIXXX_USE_QOPENGL -DT_LINUX -g -fvisibility=hidden -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -mtune=generic -o CMakeFiles/fidlib.dir/lib/fidlib/fidlib.c.o -c /home/uk/volumes/Build/cpp/mixxx/lib/fidlib/fidlib.c

**Comment by uklotzde** [comment] 2023-04-17 08:36
Let's burn the C/C++ toolchain. After multiple rebuilds with previously wiping the `ccache` cache it turns out that this issue affects all GCC 13 builds, independent of the optimization settings.

With Clang it still works as expected.

**Comment by hapst3r** [comment] 2023-04-17 09:38
I have suggested to close #11409 cause your issue is more comprehensive and you seem to know your way around debugging much better than I do. Thus, I will try to contribute to this issue to the extent that I can and it makes sense.

For now, the only thing I can meaningfully contribute is to echo that when using `clang` instead of `gcc`, the problems mentioned in both issues don't appear. 

I did `git checkout 2.3.4` beforehand, because as mentioned before both `main` and `2.4` prompt me for `qt5qml` which is not available on my distro (openSUSE Tumbleweed).

The steps I took
```
cd /path/to/mixxx/repo
rm -rf ./build
export CC=/path/to/clang
export CXX=/path/to/clang++
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -S /path/to/mixxx/repo
cmake --build /path/to/mixxx/repo --parallel `nproc`
```

Afterwards, running `/path/to/mixxx/repo/build/mixxx` works including the problematic functionalities in question (waveform, eq).

If there is anything I can contribute to the resolution even given my non-existent c++ skills, feel free to tell me what to do :)

**Comment by daschuer** [comment] 2023-04-17 22:52
@uklotzde @hapst3r 
I have just added a test with that check the waveform analyzer with a simple rectangular jump wave. 
Please check if you are able to fail this test. If not, I need to use a real track for reference. 
https://github.com/daschuer/mixxx/tree/analyzerwavefromtest_2
```
git checkout -b analyzerwavefromtest_2 2.3
git pull https://github.com/daschuer/mixxx.git analyzerwavefromtest_2
```

**Comment by hapst3r** [comment] 2023-04-18 21:07
> @uklotzde @hapst3r I have just added a test with that check the waveform analyzer with a simple rectangular jump wave. Please check if you are able to fail this test. If not, I need to use a real track for reference. https://github.com/daschuer/mixxx/tree/analyzerwavefromtest_2
> 
> ```
> git checkout -b analyzerwavefromtest_2 2.3
> git pull https://github.com/daschuer/mixxx.git analyzerwavefromtest_2
> ```

The build process terminates prematurely: [230418-analyzerwavefromtest_2-build.log](https://github.com/mixxxdj/mixxx/files/11266355/230418-analyzerwavefromtest_2-build.log).

Nonetheless, here's the ctest: [230418-analyzerwavefromtest_2-ctest.log](https://github.com/mixxxdj/mixxx/files/11266362/230418-analyzerwavefromtest_2-ctest.log)

After the `git checkout` and `git pull`, I had to manually merge files, which I find surprising.

**Comment by uklotzde** [comment] 2023-04-18 21:38
I am not planning to spend more time and resources on analyzing these issues. Switching to Clang works for me for the time being.

Keeping this ancient C code working is a huge technical risk for the future of Mixxx.

**Comment by daschuer** [comment] 2023-04-18 21:40
@hapst3r I guess your 2.3 branch was not clean before 
you can reset the branch to the original state by: 
```
git reset 0a85171 --hard
```

**Comment by Swiftb0y** [comment] 2023-04-19 21:01
good news I guess, https://github.com/daschuer/mixxx/tree/analyzerwavefromtest_2 fails
```
Note: Google Test filter = AnalyzerWaveformTest.canary
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AnalyzerWaveformTest
[ RUN      ] AnalyzerWaveformTest.canary
Warning []: Buffer does not match "AnalyzerWaveformsTest" , actual buffer written to  "reference_buffers/AnalyzerWaveformsTest.actual"
/home/swiftb0y/Sourcerepositories/mixxx/src/test/analyserwaveformtest.cpp:84: Failure
Value of: false
  Actual: false
Expected: true
Warning []: Buffer does not match "AnalyzerWaveformSummaryTest" , actual buffer written to  "reference_buffers/AnalyzerWaveformSummaryTest.actual"
/home/swiftb0y/Sourcerepositories/mixxx/src/test/analyserwaveformtest.cpp:84: Failure
Value of: false
  Actual: false
Expected: true
[  FAILED  ] AnalyzerWaveformTest.canary (40 ms)
```

**Comment by Swiftb0y** [comment] 2023-04-19 21:03
I assume you'll want to conduct some tests on the results?
[AnalyzerWaveform.zip](https://github.com/mixxxdj/mixxx/files/11277568/AnalyzerWaveform.zip)

**Comment by daschuer** [comment] 2023-04-20 22:09
It looks like I have found a GCC 13 bug. The -HUGE_VAL is optimized away which makes fidlib go wild. 
This demonstrates the issue: 
https://godbolt.org/z/7bnb77hv4

**Comment by daschuer** [comment] 2023-04-20 22:34
I have reported it upstream: 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109581

**Comment by apinski-cavium** [comment] 2023-04-20 22:39
> It looks like I have found a GCC 13 bug. The -HUGE_VAL is optimized away which makes fidlib go wild. This demonstrates the issue: https://godbolt.org/z/7bnb77hv4

And it is not a GCC 13 bug, especially when you use -ffast-math/-ffinite-math-only .

**Comment by Swiftb0y** [comment] 2023-08-07 19:07
This can be closed, right?

**Closed** 2023-11-06 20:31 UTC
Labels: bug, confirmed
