### ISSUE TITLE
Mixxx crashes on bootup after upgrading to Ventura

### ISSUE THREAD

**Issue by ronr255** [mixxxdj/mixxx#11192] opened 2023-01-09 03:16 UTC
### Bug Description

Everything was fine, but my mac mini M1 was having graphics card issues.  Apple sugested I go ahead and update to Ventura.  I did, and the old version of Mixxx would crash on opening.  I downloaded the latest version of Mixxx hoping it would be fixed, but it, too, has the same crashing error.  Can someone point me in the right direction?

[Mixxx Crash Data.rtf.txt](https://github.com/mixxxdj/mixxx/files/10370153/Mixxx.Crash.Data.rtf.txt)

### Version

2.3.3

### OS

Mac OS Ventura 13.0.1

**Comment by daschuer** [comment] 2023-01-09 08:15
This is a duplicate of: 
This seems to be similar to https://github.com/mixxxdj/mixxx/issues/11019

```
Crashed Thread:        47  com.apple.audio.IOThread.client
Exception Type:        EXC_CRASH (SIGABRT)
libportaudio.2.dylib          	       0x10a60c859 AudioIOProc + 1193\
```

Does the latest 2.3 branch still crash? 
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-116-g3c6694f23e-macosintel.dmg

You may also try out the unofficial native 2.4-alpa M1 build from my private repository:   
https://github.com/daschuer/mixxx/suites/10244878232/artifacts/502509291
(You need to be logged in to GitHub to make that link work)

Please report your results.

**Comment by daschuer** [comment] 2023-01-10 12:23
@ronr255 has confirmed that the both builds are working here: https://github.com/mixxxdj/mixxx/issues/11019

**Closed by daschuer** 2023-01-10 12:23 UTC
Labels: duplicate, bug, confirmed
