### ISSUE TITLE
macOS: use preferred language instead of region for Mixxx > Interface > Locale when set to `System`

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#11899] opened 2023-08-30 23:35 UTC
### Feature Description

macOS 13.5.1
Mixxx 2.5-alpha-84-gde4e2cca61 (main)
Qt 6.5.2

macOS System Settings > General > Preferred Languages: English – Primary
Region: Germany

With `Mixxx > Settings > Interface > Locale` set to `System`

**Currently**
German locale is used

**Expected**
English locale should be used

Not sure why this is, probably because Region is used instead of preferred language (primary).

**Comment by daschuer** [comment] 2023-08-31 07:03
This sounds like a duplicate of: 
https://github.com/mixxxdj/mixxx/issues/11195
Fixed in 
https://github.com/mixxxdj/mixxx/pull/11218/files
The fix is guarded by Qt Versin < 6.2.0
Maybe it is not fixed yet?

**Comment by foss-** [comment] 2023-08-31 07:14
Indeed, I even verified the fix back then. What do you mean with "fix is guarded by Qt Version < 6.2.0"?

**Comment by daschuer** [comment] 2023-08-31 07:23
Or just open a PR and use the created binary. 

I think we should also reopen the upstream bug and verify if our fix is still correct.

**Comment by daschuer** [comment] 2023-09-04 09:58
Not sure if this is a bug of feature: 
What does 
`echo $LANG`
`echo $LC_NUMERIC`
and 
`echo $LC_ALL`
return? 

There seems to be a pending issue
https://bugreports.qt.io/browse/QTBUG-90972
is it yours? 

The original bug is fixed here:
https://github.com/qt/qtbase/commit/d8158c6c93fc2a83f5acacc7baaf1a840951cf1e


> If we want to support LANG or other environment variable overrides,
they should be handled by the layer above the system locale, by
changing the default locale of the Qt application, as if the user
had called QLocale::setDefault(). 

This reads as if LANG is used/implemented as an override in Qt. 

I have also found this about the CFLocaleCopyCurrent() Qt makes use of: 
https://developer.apple.com/documentation/corefoundation/1542508-cflocalecopycurrent

It suggests to use: CFLocaleCopyPreferredLanguages()
https://developer.apple.com/documentation/corefoundation/1542887-cflocalecopypreferredlanguages

**Comment by foss-** [comment] 2023-09-07 09:10
> What does `echo $LANG` `echo $LC_NUMERIC` and `echo $LC_ALL` return?

No output when issuing those commands in terminal.

> There seems to be a pending issue https://bugreports.qt.io/browse/QTBUG-90972 is it yours?

Not my issue. Sounds like the correct feature request that would resolve this issue. Sadly despite being assigned for over 2 years, the feature is not yet implemented and it seems no development is happening.

Thanks for looking into this.

**Comment by daschuer** [comment] 2023-09-07 14:31
No output is a reasonable result. 
That rules out the issue that there is something wrong with environment variables.

**Comment by daschuer** [comment] 2024-12-02 12:31
We are now at Qt 6.5.3 for macOS  so I consider this fuly fixed. Please reopen if ther is anything left to do.

**Closed by daschuer** 2024-12-02 12:31 UTC
Labels: preferences, regression, bug, QT6
