### ISSUE TITLE
Won't install on Ubuntu 22.10 Kinetic Kudu

### ISSUE THREAD

**Issue by xmready** [mixxxdj/mixxx#11002] opened 2022-10-25 01:23 UTC
### Bug Description

After adding the repository to a fresh ubuntu kinetic and updating the package lists, the install fails with the following error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mixxx : Depends: libavcodec58 (>= 7:4.4) but it is not installable
         Depends: libavformat58 (>= 7:4.4) but it is not installable
         Depends: libavutil56 (>= 7:4.4) but it is not installable
         Depends: libswresample3 (>= 7:4.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
After looking around, I can't find these packages listed anywhere in the kinetic repos. Would love to play around on this software if I can get it working.

### Version

2.3.3

### OS

Ubuntu 22.10

**Comment by ronso0** [comment] 2022-10-25 23:00
So ffmpeg was updated to 7:5.1.1-1ubuntu1 three weeks ago and the the dependencies need to be updated?
https://launchpad.net/ubuntu/kinetic/+source/ffmpeg

libavcodec5**9**
libavformat5**9**
libavutil5**7**
libswresample**4**

**Comment by daschuer** [comment] 2022-10-26 12:29
I can confirm that the package was build with the old ffmpeg: 
https://launchpad.net/~mixxx/+archive/ubuntu/mixxx/+build/24101578/+files/buildlog_ubuntu-kinetic-amd64.mixxx_2.3.3-1~kinetic_BUILDING.txt.gz

As a workaround you can use the Ubuntu package: "2.3.2~dfsg-1build1"
It has been already rebuild against libavcodec59

**Comment by daschuer** [comment] 2022-10-26 12:43
I have deleted the Kinetic package that it will automatically fall back to the Ubuntu package. 
The alternative is to use the beta PPA with ppa:mixxx/mixxxbetas with 2.3.3+29+g82043dfd32-1~kinetic 

Once we have the 2.3.4 the issue is gone. I would like to work on hat instead of doing a mixxx_2.3.3-2~kinetic.

**Comment by xmready** [comment] 2022-10-26 21:54
Ok i'll wait until the next version before I install it.

**Comment by daschuer** [comment] 2023-03-15 10:12
We have now a 2.3.4 release https://launchpad.net/~mixxx/+archive/ubuntu/mixxx/+packages
Depending on:
libavcodec59 
libavformat59 
libavutil57 
libswresample4

So this issue should be fixed. Please reopen if this is not the case.

**Closed by daschuer** 2023-03-15 10:12 UTC
Labels: bug, confirmed, packaging
