### ISSUE TITLE
Unable to double/half loops if they aren't a round or fractionnal beatgrid value

### ISSUE THREAD

**Issue by acolombier** [mixxxdj/mixxx#12553] opened 2024-01-12 10:08 UTC
### Bug Description

(Apologies, I couldn't decide between the feature request and bug report. The second point of `Actual behavior` is however quite impacting so I thought the later would do)

*Scenario*

- Set a beatgrid loop (say 1 beat) and activate with `beatloop_activate`
- Adjust the loop in/out cue (for example, using a loop mode on a controller)
- Half or double the loop using `loop_double` or `loop_halve` control

*Actual behavior*

- The beatgrid value as represented by `beatgrid_size` gets updated but the loop cues don't get changed
- After exiting the loop, It is sometime impossible to re-create a loop using `beatloop_activate` (not consistent, hard to reproduce)

*Suggested behavior* 

- Out of Quantize mode, the loop size should be doubled or halved: if the loop was 0.98 beat and it gets doubled, it should be 1.96 beat.
- In Quantize mode, the new loop size should be adjusted to the nearest beatgrid size: if the loop was 0.98 beat and it gets doubled, it should be rounded to 2 beats

If you are happy with this behavior extension, I'm happy to look at implementing it! :) 

### Version

main

### OS

Pop OS 22.04 (with Wayland)

**Comment by ronso0** [comment] 2024-01-12 10:21
Thanks for you report.

Despite the different setting this is a dupe of #10511  and can be fixed by #12522. Though that has some side effects and there are valid reasons for the current implemantation, so please share you thoughts / use case in #12522.
Thanks!

**Closed by ronso0** 2024-01-12 10:21 UTC
Labels: bug
