### ISSUE TITLE
Removing a track from history list set all play counters to 0

### ISSUE THREAD

**Issue by MarcPlace** [mixxxdj/mixxx#12256] opened 2023-11-04 15:46 UTC
### Bug Description

Yesterday I fell over a nasty bug in Mixxx 2.4.0 using e3e0f6e669457c7de78f1e4fa5bee695eee42fda, but it also happened a few weeks ago. Unfortunately I didn't know what was the cause for it so I did some investigations today.

Track list looks like this ("Played" counter is set to 1 or more):
![shot01](https://github.com/mixxxdj/mixxx/assets/71196229/273ecc75-c3fa-4ed3-af6d-7715e8ddef90)

Then I go to the "History" crate and remove a track from the list:
![shot02](https://github.com/mixxxdj/mixxx/assets/71196229/1e5423f0-4cf2-441d-8c1b-5ae18829e0cf)

After restarting Mixxx, all "Played" counters are now set to 0 (funny: the track I removed from the list seems to be OK and the counter has still 3 plays):
![shot03](https://github.com/mixxxdj/mixxx/assets/71196229/ac78fc9a-4a5f-4ef8-9f33-cc666a589549)

Luckily I had a backup of "mixxxdb.sqlite" file with me, so I could quickly restore all the settings again (keep this in mind if you try to reproduce this issue :-) )

Hope this helps for digging into it to confirm this issue.

Kind regards,
Marco

### Version

2.4.0

### OS

Gentoo Linux

**Comment by uklotzde** [comment] 2023-11-04 16:17
Good job and excellent bug report! You were able to reproduce #12046 which was reported earlier.

@Swiftb0y Mark #12064 as a duplicate and continue here?

**Comment by MarcPlace** [comment] 2023-11-04 16:25
Sorry, I've crawled the bug reports before of course, but haven't found anything similar to my issue. But #12046 looks indeed like something related to mine. Glad that I could help you.

**Comment by uklotzde** [comment] 2023-11-04 16:38
The query `updateNotPlayed` in `TrackDAO::updatePlayCounterFromPlayedHistory()` seems to be the cuplrit.

**Comment by uklotzde** [comment] 2023-11-04 16:41
I'll fix it. Looks like a closing brace in the SQL statement is misplaced.

**Comment by uklotzde** [comment] 2023-11-04 16:48
The bug only affects the code path for SQLite >= 3.33.0 that makes use of _UPDATE-FROM_.

**Comment by Swiftb0y** [comment] 2023-11-04 17:00
> The bug only affects the code path for SQLite >= 3.33.0 that makes use of UPDATE-FROM.

That would likely explain why the devs on ubuntu 20.04. did not experience this issue. 

> I'll fix it. Looks like a closing brace in the SQL statement is misplaced.

Thank hugely you for identifying and fixing the problem. Please ping me in your fix, I will review it ASAP.

**Comment by uklotzde** [comment] 2023-11-04 18:05
As a bonus I have added the SQL statement that restores the lost data: https://github.com/mixxxdj/mixxx/pull/12258/commits/0083a21d96f7bdb878a04d0b19bffa4c119ef001

Could also be executed as part of a database migration or triggered on demand.

**Comment by MarcPlace** [comment] 2023-11-04 21:01
Did a quick test and can confirm, that 0083a21d96f7bdb878a04d0b19bffa4c119ef001 has fixed this issue (at least for me). 👍

The SQLite version that Gentoo 17.1 offers looks quite recent:
marco@timmy ~ $ sqlite3 --version
3.43.2 2023-10-10 12:14:04 4310099cce5a487035fa535dd3002c59ac7f1d1bec68d7cf317fd3e76948alt1 (64-bit)

I think all most recent distributions are using SQLite >3.33.0 for now (except Ubuntu Focal as mentioned above).
Anyway guys, thanks for tracking this issue down that fast. 🎉

**Comment by Swiftb0y** [comment] 2023-11-05 11:41
fixed in 2.4. Thank you uklotzde for the fix and thank you marc for the detailed bug report.

**Closed by Swiftb0y** 2023-11-05 11:41 UTC
Labels: bug
