### ISSUE TITLE
Stem Separation

### ISSUE THREAD

**Issue by MaxDeepCoder** [mixxxdj/mixxx#11428] opened 2023-03-31 22:44 UTC
### Feature Description

I would love stem separation so I can do Live DJ mixes instead of using paid software! I think it's a great feature but could be quite hard to implement! There are great models like Deezer's sepearation. 

Thanks!

**Comment by Holzhaus** [comment] 2023-03-31 23:50
Duplicate of #11391.

**Closed by Holzhaus** 2023-03-31 23:50 UTC
Labels: duplicate, feature

**Comment by MaxDeepCoder** [comment] 2023-04-01 12:07
Thanks
