### ISSUE TITLE
Deleted files are still present in crates after library scan

### ISSUE THREAD

**Issue by dustinpaluch** [mixxxdj/mixxx#13415] opened 2024-06-27 22:05 UTC
### Setup:
I have my music library in a single folder on an internal hard drive and mixxx has scanned and can play all the files. Some tracks are added to a crate.

### To reproduce:
2. Delete a track with your OS file browser that was inside of a crate.
3. Click Library > Rescan Library

### Expected:
The track is removed from the library and the crate.

### Actual:
The track is removed from the library but NOT the crate.

### Version

2.4.1

### OS

macOS Sonoma 14.3.1

**Comment by ronso0** [comment] 2024-06-27 22:27
Thanks for this report, though this is a dupe of #9365 
Missing tracks are not automatically removed from carefully curated track sets (crates or playlists) in order to not destroy those. This covers the case where a directory is missing during a library rescan (e.g. because it's in a currently unmounted drive).
You need to purged missing tracks manually in Tracks -> Missing.

FYI in Mixxx 2.5 missing tracks are marked (in playlists and crates) with red text so you know at a glance.

**Closed by ronso0** 2024-06-27 22:27 UTC
Labels: bug
