### ISSUE TITLE
Pitch of deck 1 is changing when skipping on paused deck 2

### ISSUE THREAD

**Issue by Russe** [mixxxdj/mixxx#11788] opened 2023-08-04 11:37 UTC
### Bug Description

1. Load track 1 to deck 1
2. Play deck 1
3. Enable Sync for deck 1
4. Enable Quantize for deck 1
5. Load track 2 to deck 2
6. Enable Sync Leader for deck 2
7. Keep deck 2 paused
8. Click with mouse at deck 2 on waveform that paused track 2 will get a different position
9. Now playing deck 1 will get a sound pitch
10. Repeat point 8 and 9

This seems to be only when sync on both decks is enabled, sync leader is deck 2 and deck 1 is quantized

Please let me know when I should do some other tests.

### Version

2.4.0-beta

### OS

Ubuntu 22.04.2

**Comment by daschuer** [comment] 2023-08-05 09:39
Is 2.3.5 also affected or is this a 2.4.0 regression?

**Comment by Russe** [comment] 2023-08-06 10:35
I can not reproduce it with 2.3.5
Maybe because there's no Sync Leader option?

**Comment by Swiftb0y** [comment] 2023-08-06 11:48
No, sync leader has been introduced in 2.4.0. Bringing @ywwg into the loop since they implemented the sync leader feature.

**Comment by ronso0** [comment] 2023-08-14 23:10
Addressed by #11831, no?

**Comment by daschuer** [comment] 2023-08-15 07:50
Bug or feature? 
We have decided that following every temp change from deck 1, in you case, should become the new default behaviour for Mixxx 2.4.
Without key-lock enabled, this cause a steady pitch change (yowling sound) in the follower track. 

The workaround is to open ~/.mixxx/mixxx.cfg and add 
`sync_lock_algorithm = 1` 
to the `[BPM]` section 

This will restore the 2.3 behaviour where both tracks are synced to a steady tempo.
With the "LateNight" skin, you can still select explicit one deck as leader by clicking on the "crown" button and make a follower deck following dynamic tempo changes of the selected leader.

https://github.com/mixxxdj/mixxx/pull/11828 exposes this hidden setting in the deck preferences.

**Comment by ywwg** [comment] 2023-11-22 20:09
This edge case is occurring because you are seeking deck2 unquantized, which means now deck 1 is out of phase with deck 2.  The sync algorithm needs to speed up or slow down deck 1 to get it back in line with deck 2, otherwise deck 1 is not quantized to deck 2 as requested.

There are a few user fixes:

1. Enable quantize on deck 2 as well.  That way when you seek, you'll seek to an even beat and there should not be any de-sync.
2. Enable keylock on deck 1 to prevent warbling (aka yowling).
3. Don't do that -- you should probably have deck 1 be the Leader and then you can jump around in deck 2 without causing a problem. OR, let Mixxx pick the leader.

A possible programmatic fix would be to call sync-quantize on deck 1 when the seek on deck 2 occurs -- this is risky from a musical perspective, but so is randomly jumping around on another deck without respect for beat matching.

Given the three workarounds I would propose not to fix this. If you have a valid musical use-case for setting up the decks like this, I would like to hear it, but as it is it sounds like an artificial situation that would not happen in a live context.

**Comment by Russe** [comment] 2023-11-26 21:17
When doing a gig I often switch between sync and manual mixing, because I have a lot of analog recorded tracks with old equipment (beat is often moving around). Sometimes I end up in this situation with headphones on to search in deck 2, and I don't recognize the yowling of deck 1 which is playing for the crowd :-(
In my opinion there should be no change to the sound of deck 1 when skipping in deck 2 which is muted.

But I will check the settings which are introduced with #11828

**Comment by Russe** [comment] 2023-11-27 22:37
Thanks.
I will have a look at this within the next weeks.
As well I try to recognize what I'm exactly doing that will cause this situation.

Do I need to build Mixxx by myself to test the your code or is there a way to change this somewhere at standard beta installation?

**Comment by ronso0** [comment] 2023-11-27 22:39
Yes, you need to apply the changes @ywwg proposed to the code base and compile Mixxx.
Though that requires some testing to be sure it doesn't cause other issues.

**Comment by Russe** [comment] 2023-11-27 22:49
Currently I have no environment to compile Mixxx, but I will set up one in the next time. This can take some weeks, currently I'm very busy with other tasks.

**Comment by ywwg** [comment] 2023-12-02 17:39
I can whip up a PR with this change and we can make a build available to you

**Comment by ywwg** [comment] 2023-12-02 19:09
The build succeeded but I'm not sure where the artifact uploaded to: https://github.com/mixxxdj/mixxx/actions/runs/7071856992/job/19250031825?pr=12388

**Comment by Russe** [comment] 2023-12-03 21:21
Thanks a lot for your work, I hope I can test this within the next weeks.

Btw, the artifacts are here: https://github.com/mixxxdj/mixxx/actions/runs/7072994159
From pull request you need to go to "Checks" and then to "Build", then scroll to bottom of the page.

**Comment by daschuer** [comment] 2023-12-06 17:36
This issue becomes worse, if the stopped leader has dynamic tempo. Than a seek like you do when cuing up can change the playing follower.

**Comment by ywwg** [comment] 2023-12-07 00:41
I added a reply in the PR.  I agree the current solution is still not great.  I wonder if a simpler solution is just to make the "explicit" button only update which deck is the "implicit" leader. That might be sufficient

**Comment by ywwg** [comment] 2023-12-12 20:50
https://github.com/mixxxdj/mixxx/pull/12431

**Closed** 2023-12-15 18:49 UTC
Labels: regression, bug, confirmed, sync

**Comment by ywwg** [comment] 2023-12-15 19:01
We should also merge the manual update
https://github.com/mixxxdj/manual/pull/600

**Comment by Russe** [comment] 2023-12-17 11:11
Excellent, thanks for resolving this issue. I tested the most recent beta, now the problem should never happen again.
