### ISSUE TITLE
When midi controller disconects it won't reconnect

### ISSUE THREAD

**Issue by didgewind** [mixxxdj/mixxx#12428] opened 2023-12-12 10:11 UTC
### Bug Description

When I am using mixxx with a midi controller, when the controller disconnects it won't connect again. Or, when I launch mixxx with my controller disconnected, it won't be recognised by mixxx when connecting it.

### Version

2.3.6

### OS

LUbuntu 22.04 (Ubuntu with LXQT)

**Comment by ronso0** [comment] 2023-12-12 12:09
Unfortunately Mixxx doesn't support hot-plug yet. This is a limitation of the library currently used for handling controllers.

> You can also try to reconnect it by going into options and disabling the midi controller, applying, then activating it again. In some cases, mixxx will pick up the controller without restart.

Duplicate of #5614

**Closed by ronso0** 2023-12-12 12:09 UTC
Labels: bug
