### ISSUE TITLE
deleted tracks are not moved to Missing after rescan

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#12239] opened 2023-10-30 16:03 UTC
### Bug Description

Since today Mixxx isn't able to clean the database from deleted tracks. Normal deleted tracks come in the "missed tracks" window after rescanning. That isn't working. The tracks appear in the normal database search - but can't load

### Version

2.4 beta 205

### OS

Linux Mint 21.2 Cinnamon

**Comment by stefan-franz** [comment] 2023-10-30 16:26
Now after closing and reopen it worked. Or it took more time as i expected. I have about 24.000 songs on my SSD - Don't know how fast the database is and what time is here normal. 

It works - take only more time or closing and reopen.

**Comment by stefan-franz** [comment] 2023-10-30 16:41
Tested again - now it works normal. All good.

**Comment by ronso0** [comment] 2023-10-30 16:44
Closing & reopening should not be required.
Also, if scanning takes some time you should see a progress dialog
![image](https://github.com/mixxxdj/mixxx/assets/5934199/1f36a9e6-7d87-4140-8b5c-7b7ce9e2ea6a)

So you can now confirm deleted tracks show up in Missing?

**Comment by stefan-franz** [comment] 2023-10-30 16:55
Yes all works fine. The dialog doesn't appear - or maybe if Mixxx has to scan neu and fresh 1000 of songs....if i go to Bibliothek / New scan, Mixxx make this without a message....hmmm....but it works.  all ok.

**Comment by uklotzde** [comment] 2023-10-30 17:41
Restarting Mixxx has no effect for detecting missing files.

Any concurrent database operations may fail by chance. You will only notice this when examining the log file.

Mostly happens when the library scanner is active. It runs in a separate thread and uses long running transactions: https://github.com/mixxxdj/mixxx/issues/6631

**Comment by ronso0** [comment] 2023-11-08 22:48
So, as a **quick** fix for this sort of issues, would it be sufficient (as proposed in https://github.com/mixxxdj/mixxx/issues/6631#issuecomment-1225409936):
* show the scan dialog immediately
* make it modal so no transactions can be triggered

?
@uklotzde What do you think?

**Comment by uklotzde** [comment] 2023-11-08 23:42
> So, as a **quick** fix for this sort of issues, would it be sufficient (as proposed in [#6631 (comment)](https://github.com/mixxxdj/mixxx/issues/6631#issuecomment-1225409936)):
> 
>     * show the scan dialog immediately
> 
>     * make it modal so no transactions can be triggered
> 
> 
> ? @uklotzde What do you think?

So effectively disable the threading mechanics of library scanner? :sweat_smile: Maybe. Not sure if it is worth the effort.

**Comment by stefan-franz** [comment] 2023-12-28 08:18
Whould be nice, if that bug can repaired the next days.....

**Comment by ronso0** [comment] 2023-12-28 13:33
You already posted exactly that earlier ; )

So the issue is still that you don't see the rescan dialog?

**Comment by stefan-franz** [comment] 2023-12-29 05:15
No, the rescan was always shown. But the database doesn't clean the deleted files. 
Now it seems to work. You can close it. If i recognize the error again, i'd report it.

**Closed** 2023-12-29 06:57 UTC
Labels: bug
