### ISSUE TITLE
Support Apple Silicon ARM64 M1 M2

### ISSUE THREAD

**Issue by mbacarella** [mixxxdj/mixxx#10907] opened 2022-09-19 16:07 UTC
### Feature Description

I understand this is being worked on but thought I would create an issue so that there's a focal point for discoverability. I just tried to cmake the head of the mixxx repo and got a bunch of link failures for arm64. 

Is there a branch I can try? Any tasks I can look into?

**Comment by fwcd** [comment] 2022-09-20 01:15
Check out

- https://github.com/mixxxdj/mixxx/issues/10867
- https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/macos.20apple.20silicon (I think this was the most recent thread)

For ready to run (but unofficial alpha) builds

- https://github.com/daschuer/mixxx/actions/runs/2638298438
- https://github.com/fwcd/m1xxx

To summarize, the issue is that we need to build a patched version of Qt 5.12 which is non-trivial and work to upstream these patches (at least to the Mixxx repos, including [the vcpkg fork](https://github.com/mixxxdj/vcpkg) is happening, but will probably take a while.

**Comment by mbacarella** [comment] 2022-09-20 02:45
Ah, nice. I wanted to build mixxx on my M2 to work on unrelated-to-Apple-Silicon features. I presume your m1xxx repo is the way to go for that.

**Comment by fwcd** [comment] 2022-09-20 02:49
That repo is more of a workaround for now, since I was personally interested in having a central place to track a working configuration for building Mixxx on Apple Silicon. In the medium-term though we'd of course want upstream to build directly on ARM macOS.

**Comment by fwcd** [comment] 2022-09-20 03:00
For building Mixxx on your own Apple Silicon machine, you might also find these useful:

- The CI workflow that performs this build (although it cross-compiles from an x86_64 macOS runner): https://github.com/fwcd/m1xxx/blob/main/.github/workflows/build.yml
- This writeup (though it might be outdated, haven't checked in a while): https://gist.github.com/fwcd/6ef98ddfc68629f4f0dd5703386c245e

Also the branches of `mixxx` and `vcpkg` that `m1xxx` point to, while they should work, are probably outdated. You might want to check @daschuer's forks for more recent versions.

**Comment by fwcd** [comment] 2022-09-20 03:24
(Also note that if you're just interested in working on features, you can always build Mixxx under Rosetta, which should work with the exact instructions from this repo and the `main` branch)

**Comment by daschuer** [comment] 2023-05-18 20:08
Fixed since: https://github.com/mixxxdj/mixxx/pull/11398

**Closed by daschuer** 2023-05-18 20:08 UTC
Labels: feature, confirmed
