### ISSUE TITLE
Precompiled heades (PCH) should be opt-in and not opt-out

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#12316] opened 2023-11-19 21:41 UTC
### Bug Description

Pre-compiled headers seem to cause more issues than benefits.

Requiring to explicitly opt-out by specifying `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON` is not intuitive.

**Comment by daschuer** [comment] 2023-11-19 22:47
Please describe your issues. 
Is this a duplicate of https://github.com/mixxxdj/mixxx/issues/12081?

**Closed** 2023-11-19 23:12 UTC
Labels: build, bug
