### ISSUE TITLE
Have the "Reset BPM" in the "Adjust BPM" submenu only restore BPM to before any new user change, not fully clear the BPM and beatgrid?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12774] opened 2024-02-09 21:29 UTC
### Feature Description

It would be nice to reset an altered BPM to the number that it was before (on load to the deck I guess), rather than clear the beatgrid, which then requires the extra step of Analysing the track again to get back to where things were.

There's already "BPM and beatgrid" in the "Reset" submenu.

A new phrasing to differentiate? Personally I think "Reset" would be turning it back to the prior number, where as something like "Clear" would be a clearer title for the "Reset" submenu, but if the meaning of "Reset" stays the same, then the "Adjust BPM" reset entry could be maybe "Restore BPM" instead?

**Comment by ronso0** [comment] 2024-02-09 23:56
Hmm, IIUC that would require to store the previous beats (BPM + beat map/grid) per track, at least for the current session.

**Comment by ronso0** [comment] 2024-02-15 14:16
I agree with the unclear phrasing Reset / Clear.

Never the less, in order to implement Reset (revert to track's database state from when Mixxx was started) it had to keep a dupe of the entire db or just modified tracks. Not sure if that is feasible, effort (implementation + maintenance) vs. benefit

**Comment by mxmilkiib** [comment] 2024-03-11 20:30
Arguably a dupe of #10138

**Comment by ronso0** [comment] 2024-03-12 02:42
> "Clear" would be a clearer title for the "Reset" submenu

Do you mind opening a PR?
The sooner the better as it increases the probability translators adjust the translations.

**Comment by ronso0** [comment] 2024-03-12 16:02
> It would be nice to reset an altered BPM to the number that it was before (on load to the deck I guess)

Fixed by 12954.
Applies to all BPM/beats changes (decks and library track menu).

> on load to the deck I guess

This is more elaborate than simply tracking BPM/beats changes in the track object itself.
Also when the track is (re)analyzed the "on load to the deck" state might be 0.
I propose to go with the general implementation #12954.
Please test!

**Closed** 2024-05-14 18:40 UTC
Labels: library, feature, bpm

**Comment by ronso0** [comment] 2024-05-14 20:33
Please note that #12954 only adds the control, no skin implementation, yet.
