### ISSUE TITLE
Deck waveform rendering inconsistently 

### ISSUE THREAD

**Issue by idcmp** [mixxxdj/mixxx#11412] opened 2023-03-28 07:04 UTC
### Bug Description

Sometimes when a deck gets a track, the waveform is rendered in such a way that it "ends early" (ie, there's just ------ at the end). If I drag the track onto the deck, or double click it for another deck, it will usually render okay.

I tried bringing in a new song (that hadn't been analyzed) and it had this issue too.

See: https://mixxx.zulipchat.com/#narrow/stream/267968-testing/topic/macos.20waveform.20rendering.20bugs.3F

This seemed to start happening on my 2.3.4 upgrade.

### Version

2.3.4

### OS

macOS Ventura (m2 max)

**Comment by daschuer** [comment] 2023-03-28 07:20
I assume this bug is a duplicate of https://github.com/mixxxdj/mixxx/issues/11344 and should be fixe in the latest build from our 2.3 branch https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.4-18-g9db1ac195f-macosintel.dmg

**Comment by obsoleszenz** [comment] 2023-03-28 09:11
I have the same on linux with 2.3.4

**Comment by foss-** [comment] 2023-03-28 11:16
@obsoleszenz is the issue persisting with a 2.4 test build from https://mixxx.org/download/#testing?

**Comment by obsoleszenz** [comment] 2023-03-28 11:21
> @obsoleszenz is the issue persisting with a 2.4 test build from https://mixxx.org/download/#testing?

I can use those test builds as they don't work on arch from what i know

**Comment by MarcPlace** [comment] 2023-03-28 11:30
Since we have narrowed down this issue together in #13444, I can confirm that PR #11359 has fixed it for good now. It never happened again to me after a long time now using a recent 2.3 or 2.4 development branch. In release version 2.3.4 of course, this bug is still present 'cause it was fixed afterwards. ;-)

**Comment by foss-** [comment] 2023-03-28 12:06
@daschuer do you agree, this bug should thus be closed as duplicate?

**Comment by obsoleszenz** [comment] 2023-03-28 12:07
Just tried the latest 2.3.4 branch and also didn't happen for me. I guess can be closed now :) Thanks for fixing :)

**Closed** 2023-03-28 16:28 UTC
Labels: bug, confirmed

**Comment by idcmp** [comment] 2023-03-28 18:04
Thank you!
