### ISSUE TITLE
"export playlist" replaces certain characters in filenames by ??? 

### ISSUE THREAD

**Issue by dimashenme** [mixxxdj/mixxx#11325] opened 2023-03-03 19:15 UTC
### Bug Description

Whenever I have tracks in a playlist with filenames having non-ASCII characters like

/media/dmitry/Extreme SSD/edm/VAs/Your Character - Слава україні/Binary Algorithms - Слава україні - 04 Warning.mp3
/media/dmitry/Extreme SSD/edm/VAs/Crazed Behaviour - COUNTER ATTACK/DJ これからの緊急災害 - COUNTER ATTACK - 02 I GOT 2 (B0YFR1END RESHAPE).mp3

these turn into

/media/dmitry/Extreme SSD/edm/VAs/Your Character - ????? ???????/Binary Algorithms - ????? ??????? - 04 Warning.mp3
/media/dmitry/Extreme SSD/edm/VAs/Crazed Behaviour - COUNTER ATTACK/DJ ????????? - COUNTER ATTACK - 02 I GOT 2 (B0YFR1END RESHAPE).mp3

when I export the playlist. Latin-1 characters (like à, é, ç) are handled correctly.

### Version

2.3.3

### OS

Ubuntu 20.04

**Comment by jmfergeau** [comment] 2023-08-02 08:45
m3u doesn't support thoise kind of characters. That's why the m3u8 format exists. Export the playlist in m3u8 instead of m3u and you should be fine.

**Comment by daschuer** [comment] 2023-08-02 15:05
m3u are latin-1 encoded. 
I think we can consider ??? paths as broken and so the whole playlist is broken. 
I think Mixxx should prevent to export broken m3u playlists.

What should Mixxx do instead? What was your original expectation?

**Comment by daschuer** [comment] 2023-08-02 15:23
The issue is fixed in 2.4-beta by using URL encoded paths in case of non latin-1 characters.
See: https://github.com/mixxxdj/mixxx/pull/4752

So I think we can close this as resolved.

**Closed by daschuer** 2023-08-02 15:23 UTC
