### ISSUE TITLE
Using ctrl-click as right-click freezes control after setting to default value

### ISSUE THREAD

**Issue by m0dB** [mixxxdj/mixxx#10831] opened 2022-08-28 13:11 UTC
When using the trackpad on a macbook, I use ctrl-click to emulate right-click. I found that this does not work well with mixxx: The controls (I tried with cross fade slider and any filter knob, but I assume this goes for all continuous controls) do reset to their default value as expected with right-click, but afterwards the don't respond to mouse events anymore and stay fixed at the default value, until doing a proper right click (with a mouse with physical right button) or using two-fingers-emulated-right-click. After that the control functions normally again.

(As a first time user, it took me a while to realize this was the problem when I found mixxx became gradually unresponsive.)

Using Mixxx 2.3.3 on macOS Monterey.

**Comment by ronso0** [comment] 2022-08-28 17:11
how do you configure Ctrl+click? is it a macOS-native setting or some 3rd-party app?

**Comment by m0dB** [comment] 2022-08-29 09:28
this is standard macOS behaviour (it's not even a settings, it can't be turned off unless by using 3rd party software).

**Comment by foss-** [comment] 2022-08-29 10:32
macOS 12.5.1
Mixxx 2.4-alpha-1278-gcaa494bc17 (main)

Confirming issue

The issue does not happen if mix two finger tapping touchpad as secondary click or right-click. The issue however happens if `CTRL+Click` is used. After slider is reset to default position it is no longer movable.

**Comment by ronso0** [comment] 2022-08-29 12:15
Alright, thanks for confirming.

So the issue seems to be that Mixxx recognizes the `Ctrl` keypress, then receives a `Right-click` but _no `Ctrl` release event_?
Are there more actions in Mixxx where Ctrl used? If so, can you confirm those actions are triggered even though you actually already released `Ctrl`?
For example: Ctrl+click to reset a slider/knob, (release Ctrl), click another set-off slider/knob. Is it reset?
And: say you have a (macOS-native) window next to Mixxx, if you click there is it also recognized as right-click?
What I'm trying to figure is if the `Ctrl` pressed state is stuck because Mixxx swallows the release event.

FWIW there are a few macOS-specific paths in [src/controllers/keyboard/keyboardeventfilter.cpp](https://github.com/mixxxdj/mixxx/blob/2.3/src/controllers/keyboard/keyboardeventfilter.cpp#L83-L101)

**Comment by foss-** [comment] 2022-08-29 12:28
`Ctrl-Click` continues to work in other windows outside of Mixxx after reproducing the problem in Mixxx.
When triggering a stuck slider, the other sliders remain usable until used with `Ctrl+Click` which will also lock that UI element. Easy to reproduce using the volume and cross faders.
The issue also applies to knobs e.g. head or eq knobs. Once one knob is stuck, the rest remains usable.

Is any of the console output helpful?

<details>
<summary><b>Console Output</b></summary>

```
debug	14:23:36.258325+0200	WindowServer		DHML:  P9 Wating for slide, ZInstability=0.000000, TimeInstability=0.171154 (from dtstart=0.045000s)
debug	14:23:36.258470+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f807685d6a0 event:11 sender:0x1000007c8 eventDelta:0x16b9070 deltaMS:0x5d9e3c displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x5947fbbb493
debug	14:23:36.261820+0200	WindowServer	[DEBUG] - On display 0x1b567475, surface is not detached, CoreDisplay is detached (0x00000000), DetachCode = 0
debug	14:23:36.267916+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f806c2c9ae0 event:11 sender:0x1000007c8 eventDelta:0x1fc024e deltaMS:0x5d9e45 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x594804c2671
debug	14:23:36.269184+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f807683d360 event:6 sender:0x1000007c8 eventDelta:0x21008ba deltaMS:0x5d9e47 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59480602cdd
debug	14:23:36.269280+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f80768bdc10 event:11 sender:0x1000007c8 eventDelta:0x20fca24 deltaMS:0x5d9e47 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x594805fee47
debug	14:23:36.279191+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8074faf5e0 event:6 sender:0x1000007c8 eventDelta:0x2a88c32 deltaMS:0x5d9e51 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59480f8b055
debug	14:23:36.279284+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8072d7adf0 event:11 sender:0x1000007c8 eventDelta:0x2a84e48 deltaMS:0x5d9e51 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59480f8726b
debug	14:23:36.281001+0200	Console	found no value for key NSFineScrollDelta in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281174+0200	Console	found no value for key NSWindowScrollWheelEventShouldApplyTwitterWorkaround in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281270+0200	Console	found no value for key NSScrollViewShouldDoResponsiveScrolling in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281327+0200	Console	found no value for key NSScrollViewResponsiveScrollingOptInLogToConsole in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281353+0200	Console	found no value for key NSScrollingBehaviorConcurrentEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281377+0200	Console	found no value for key NSSmoothScrollWheel in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281405+0200	Console	found no value for key NSOverlayScrollerRolloverLogicDebug in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.281558+0200	Console	found no value for key NSEventSuppressBeginEndGesture in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.290668+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f807688e500 event:6 sender:0x1000007c8 eventDelta:0x3573d27 deltaMS:0x5d9e5c displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59481a7614a
debug	14:23:36.290842+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f80768bdc10 event:11 sender:0x1000007c8 eventDelta:0x356b400 deltaMS:0x5d9e5c displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59481a6d823
debug	14:23:36.294497+0200	WindowServer	[DEBUG] - On display 0x1b567475, surface is not detached, CoreDisplay is detached (0x00000000), DetachCode = 0
debug	14:23:36.297631+0200	Console	found no value for key NSEventFractionScrollingDeltasEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297718+0200	Console	found no value for key NSScrollingBehaviorDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297812+0200	Console	found no value for key NSScrollingSingleBounceIfSwipeForwardable in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297868+0200	Console	found no value for key NSScrollingBehaviorDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297909+0200	Console	found no value for key NSScrollVelocityFilterDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297957+0200	Console	found no value for key NSScrollingBehaviorDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.297991+0200	Console	found no value for key NSScrollViewRubberbandStiffness in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.298083+0200	Console	found no value for key NSScrollViewLiveNotificationDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.298136+0200	Console	found no value for key NSScrollingBehaviorDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.298178+0200	Console	found no value for key NSScrollingBehaviorDebugEnabled in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.298214+0200	Console	found no value for key NSScrollingConcurrentVBLMonitorUsesWorkInterval in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.303325+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8074fbca80 event:6 sender:0x1000007c8 eventDelta:0x4182bea deltaMS:0x5d9e69 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x5948268500d
debug	14:23:36.303580+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8072d7adf0 event:11 sender:0x1000007c8 eventDelta:0x4178dac deltaMS:0x5d9e69 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x5948267b1cf
debug	14:23:36.311505+0200	Console	found no value for key NSScrollViewLogAllEvents in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.311602+0200	Console	found no value for key NSScrollingBehaviorDebugStateChanges in CFPrefsSearchListSource<0x6000012e2b80> (Domain: com.apple.Console, Container: (null))
debug	14:23:36.313051+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8074f56bf0 event:6 sender:0x1000007c8 eventDelta:0x4acebd4 deltaMS:0x5d9e72 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59482fd0ff7
debug	14:23:36.313183+0200	WindowServer	displayStateFilter policy:1 declareActivity:0 result:0x7f8072d7adf0 event:11 sender:0x1000007c8 eventDelta:0x4ac86c6 deltaMS:0x5d9e73 displayState:2 prevTimeStamp:0x5947e502423 eventTime:0x59482fcaae9
debug	14:23:36.322304+0200	mixxx	_CSCheckFix(11325124,org.mixxx.mixxx/2.4.0)=NOT-APPLIED
debug	14:23:36.322428+0200	mixxx	_CSCheckFix(11325124,org.mixxx.mixxx/2.4.0)=NOT-APPLIED
debug	14:23:36.322571+0200	mixxx	_CSCheckFix(11325124,org.mixxx.mixxx/2.4.0)=NOT-APPLIED
```
</details>

**Comment by ronso0** [comment] 2022-08-29 20:23
Thanksfor clarifying.
So only the slider that was reset is affected. That should simplify the fix IMO.

> Is any of the console output helpful?

Not really if I don't know how logged lines relate to Mixxx input.

**Comment by ronso0** [comment] 2022-08-29 20:44
Please test the build of https://github.com/mixxxdj/mixxx/pull/10838
See https://github.com/mixxxdj/mixxx/wiki/Testing (even though this is a very low-risk PR, backup your user data!)

**Comment by ronso0** [comment] 2022-08-29 22:46
Hmm the issue seems to be that `Ctrl`+click doesn't emit a mouse button release event.
Looking at the handler classes
https://github.com/mixxxdj/mixxx/blob/2.3/src/widget/slidereventhandler.h
https://github.com/mixxxdj/mixxx/blob/2.3/src/widget/knobeventhandler.h
there is no special right-click functionality (like right button drag or such), just the single click to reset the control.
Thus we don't need to to track the button state with `mousePressEvent` and `mouseReleaseEvent` -- we could simply use `contextMenuEvent` to reset the control.

Working on it...

**Comment by ronso0** [comment] 2022-08-29 23:48
https://github.com/mixxxdj/mixxx/pull/10839 contains the new fix to test.

**Comment by daschuer** [comment] 2022-09-12 15:49
fixed by https://github.com/mixxxdj/mixxx/pull/10869

**Closed by daschuer** 2022-09-12 15:49 UTC
Labels: macos
