### ISSUE TITLE
Leave settings dialog open when conflicting audio outputs were selected

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#13259] opened 2024-05-22 09:39 UTC
### Feature Description

I accidentally chose the same outputs for both headphones and main out. 
The dialog correctly showed a warning but after confirming the warning, the settings dialog closed immediately

![image](https://github.com/mixxxdj/mixxx/assets/25173078/3e191ce9-be28-4133-a542-a17b42cb9c35)

I want the dialog to stay open in that case so I can immediately fix the problem without having to go to the menu again to re-open the dialog first.

**Comment by ronso0** [comment] 2024-05-22 10:07
Thank you for taking the time to report this issue!
Though I'll close this since it's a duplicate of #6077 (from 2011) which also contains ideas for a fix.

**Closed by ronso0** 2024-05-22 10:07 UTC
Labels: feature
