### ISSUE TITLE
Some cover art not displaying

### ISSUE THREAD

**Issue by AlrightHector** [mixxxdj/mixxx#12133] opened 2023-10-18 00:32 UTC
### Bug Description

Some cover art is not displaying properly on the decks in 2.4 Beta. Attached image shows the tracks in the queue with the over art displayed, but on the decks it is squashed into a few lines.
<img width="598" alt="Screenshot 2023-10-18 at 01 25 02" src="https://github.com/mixxxdj/mixxx/assets/144615550/5a57214c-b39f-43db-949b-eb16bc3972f0">

### Version

2.4

### OS

Mac OS 10.14.6

**Comment by daschuer** [comment] 2023-10-18 12:09
This is a duplicate of 
https://github.com/mixxxdj/mixxx/issues/11967
Which has been fixed recently. 

I think we have not jet a signed macOs build including the fix, but you can use a unsigned build from the linked PR.

**Closed by daschuer** 2023-10-18 12:09 UTC
Labels: bug
