### ISSUE TITLE
Crashing seconds after starting on Windows 10 Pro

### ISSUE THREAD

**Issue by BounceBruhni** [mixxxdj/mixxx#10910] opened 2022-09-21 18:40 UTC
### Bug Description

I installed Mixx for the first time. 
When I started it the Mixx-Launch-Window appeared, but then after one second it crashes.
While Looking over the LOCALAPPDATA-File of Mixx, I found an XML-File named Connection 1.bcp.xml .
After reading it, I thought it could have crashed because I started it offline. But it didn't worked in Online-Mode too. 
![Connection 1 bcp xml - Editor 21 09 2022 20_39_15](https://user-images.githubusercontent.com/114104512/191584707-39dc5560-7a38-404c-96ec-2c5dd57a5245.jpg)

### Version

2.3.3

### OS

Windows 10

**Comment by farohar** [comment] 2023-02-19 19:15
This seems to be an issue with portaudio.

The installed mixxx crashed on me as well (Win 10 Pro) with nothing in the log file. So I checked the event viewer, which showed an error in ucrtbase.dll - a buffer underrun, which messes up the stack so it is not the actual error. Then I fetched the code, compiled mixxx as portable using VS2019 and it crashed there as well, following the stack trace it pointed to soundmanager.cpp line 256 on a call to Pa_Initialize():

![image](https://user-images.githubusercontent.com/7317707/219969278-eb8e8b9c-e3d1-49b5-80d0-a3aaf36de7d9.png)

Now, I am not familiar enough with the code - I just downloaded it and build it, plus cpp ain't my main coding language. Thought about rebuilding portaudio, but then I have trouble figuring out the different versions used, etc. So I just looked for another one on my box, found one, copied it to the mixxx directory and it worked.

Obviously that is not a proper solution, even if it works for me right now. Maybe someone more knowledgeable could figure how to actually build the portaudio.dll properly. The portaudio.dll I used was from my FlexAudio installation. So for anyone having trouble, they could try downloading that and using this as a workaround.

That is all the info I can provide for now.

**Comment by uklotzde** [comment] 2023-02-19 19:46
Duplicate of #10081?

**Comment by farohar** [comment] 2023-02-19 20:01
> Duplicate of #10081?

Indeed. I uninstalled FlexASIO after your comment. Replaced portaudio.dll with the one that come with mixxx and the application does start fine.

**Comment by daschuer** [comment] 2023-04-02 11:22
Closed as Duplicate

**Closed by daschuer** 2023-04-02 11:22 UTC
Labels: bug
