### ISSUE TITLE
Inconsistent Track List categories between "Computer" directories and "Crates/Playlists"

### ISSUE THREAD

**Issue by nPrevail** [mixxxdj/mixxx#11214] opened 2023-01-24 19:14 UTC
### Feature Description

I understand the difference between Crates and Playlists, and I know that Playlists are used for ordering, and Crates have no order structure and allows not duplicates.

However, from the Library Tree (far left area) with "Crates," "Playlists" and "Computer," and browsing your directories via "Computer" will give/remove some of the Track List categories. Here are the differences I see:

1. Playlist and Crates will give you the categories: color, Date Added 
2. Computer will give you the categories: ReplayGain, File Modified, Grouping, and File Created.

**Solution**
Can we have all the Track List categories available regardless of which Library Tree selection we're using (being able to see all categories in Crates, Playlists, and Computer)? If we can't enable all categories for Library, can we at least enable "File Created" and File Modified" to all Track List categories?

Personally, I like to look at my latest tracks I've added to my library, and sometimes importing my library of tracks at once (such as adding all my tracks to a new laptop) fails to show me which tracks are newer or older (Date Added will show that ALL TRACKS were added at the same time). I'm usually able to see see newer and older tracks based on using "File Created" and "File Modified."

By limiting "File Created" and "File Modified" to the "Computer" library tree, it makes it difficult to determine newer and older songs.

Thank you.

**Comment by daschuer** [comment] 2023-01-30 11:13
The difference is that the computer Tree works without library support. It shows the truth on the HD.

Related: 
https://github.com/mixxxdj/mixxx/issues/9897
https://github.com/mixxxdj/mixxx/issues/10888
https://github.com/mixxxdj/mixxx/issues/9184
https://github.com/mixxxdj/mixxx/issues/8626
https://github.com/mixxxdj/mixxx/issues/7820

Original we had plans to introduce a "folder" feature working in https://github.com/mixxxdj/mixxx/pull/1117 
Mabye we can review that part of the code.

**Comment by ronso0** [comment] 2023-10-25 13:50
Somewhat a dupe of #7028 
Let's continue the discussion there.

**Closed by ronso0** 2023-10-25 13:50 UTC
Labels: feature, confirmed
