### ISSUE TITLE
Flickering waveform display

### ISSUE THREAD

**Issue by atskler** [mixxxdj/mixxx#11243] opened 2023-02-03 15:00 UTC
### Bug Description

I observed that lately the upper waveform display started to flicker on my system when only one deck is loaded. Probably some system package was updated at some point and with that this flickering started to happen. 

Additionally: higher the frame rate, the more intense is this flickering on the upper waveform. The lower waveform just gets a stable blue background – if only that deck is loaded, and it is stable regardless of the frame rate.

Beforehand Mixxx worked correctly. I don’t know if this is a Mixxx problem or not, or will it surface for others at some point.

Anyways Mixxx works correctly without flickering if both track are loaded.

Here is how this flickering looks:
https://www.youtube.com/watch?v=UkrtMqeb-wU

### Version

2.3.3-121-gd1f63374fc

### OS

OpenSUSE Tumbleweed

**Comment by uklotzde** [comment] 2023-02-03 15:32
Probably a duplicate: #11164

**Comment by atskler** [comment] 2023-02-03 22:01
Yes, it is that issue. I checked it with the skin used in #11164

**Comment by uklotzde** [comment] 2023-03-05 18:46
@daschuer Please close this as a duplicate. I couldn't.

**Comment by JoergAtGithub** [comment] 2023-03-05 18:52
@atskler It would be great, if you could test https://github.com/mixxxdj/mixxx/pull/10989, which hopefully fixes this issue.

Duplicate of #11164

**Closed by JoergAtGithub** 2023-03-05 18:52 UTC
Labels: bug

**Comment by atskler** [comment] 2023-03-06 21:04
@JoergAtGithub how can I get the source with the fix?

**Comment by JoergAtGithub** [comment] 2023-03-06 21:10
On the bottom of each PR you find download links of the latest build: https://github.com/mixxxdj/mixxx/actions/runs/4337377093

**Comment by atskler** [comment] 2023-03-06 21:27
@JoergAtGithub yes, but there is no one rpm for OpenSUSE Tumbleweed, so I have to build it for myself, and to do that I need the _source_ with the fix.

**Comment by JoergAtGithub** [comment] 2023-03-06 21:35
Than you need to check out the PR using Git: https://github.com/mixxxdj/mixxx/wiki/Using-Git#test-a-pull-request

**Comment by ronso0** [comment] 2023-03-06 21:37
General Linux build instructions are here
https://github.com/mixxxdj/mixxx/wiki/Compiling-On-Linux

**Comment by atskler** [comment] 2023-03-06 21:57
@ronso0 yes, and usually I can build mixxx without problems.
I just need the source with the fix included because #10989 is still open and not merged into mixxxdj:main. So how can I get the source with the modifications and fixes of #10989?

**Comment by ronso0** [comment] 2023-03-06 22:04
> Than you need to check out the PR using Git: https://github.com/mixxxdj/mixxx/wiki/Using-Git#test-a-pull-request

That's one way.
My preferred way though is (if you have `gh` installed and have Mixxx forked) `gh pr checkout [PR id]`, then build.

**Comment by atskler** [comment] 2023-03-06 22:27
@ronso0 @JoergAtGithub thank you for your answers respectively, but this git ssh setup is beyond my current patience levels. If anyone can provide a wetransfer upload for the source then I can check it otherwise I will wait till it becomes merged to main.

**Comment by ronso0** [comment] 2023-03-06 22:38
At the top of #10989 you can click on the source branch `m0dB:qopengl_renderers`
![image](https://user-images.githubusercontent.com/5934199/223264312-e5952133-31a4-4a60-a847-0978f7f0bd4c.png)
There, you can click on the `<> Code` button and choose `Download ZIP` which should give you https://github.com/m0dB/mixxx/archive/refs/heads/qopengl_renderers.zip
That branch targets Mixxx' `main` branch so you need to get the respective dependencies. Idk if https://github.com/mixxxdj/mixxx/blob/main/tools/debian_buildenv.sh works on OpenSUSE though.

**Comment by atskler** [comment] 2023-03-06 23:06
@ronso0 thank you, downloaded it, but the cmake process gets derailed at:

Looking for C++ include gsl/gsl - not found
CMake Error at CMakeLists.txt:2910 (message):
  ms-gsl deveopment headers (libmsgsl-dev) not found

There seems to be no corresponding package here for libmsgsl-dev.
(I tried to installed all the available gsl packages).

**Comment by ronso0** [comment] 2023-03-06 23:33
Maybe that helps
https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/Unable.20to.20compile.20fork.20for.20PR.20work/near/287956702
or that one
https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/New.20dependency.20for.20Manjaro.20.28libmsgsl-dev.20not.20found.29

**Comment by atskler** [comment] 2023-03-06 23:45
@ronso0 thank you for the suggestions. That Microsoft stuff is plainly missing from the OpenSUSE distributions. :(

**Comment by ronso0** [comment] 2023-03-06 23:54
How about just `gsl` and/or `gls-devel`?
