### ISSUE TITLE
Relink music Directory from Linux to Windows fails

### ISSUE THREAD

**Issue by CaMeLCaseError** [mixxxdj/mixxx#12715] opened 2024-02-02 21:04 UTC
### Bug Description

Relinking Music Library paths from a Linux config on a Windows install doesn't work. The linux paths (containing slashes) seem to cause Problems when relinking - I guess it's because C:\ is prepended or the slashes aren't compatible with search and replace.
See attached screenshots for examples.

Details to reproduce: I tried to move my .mixxx settings directory and all my audio files to a windows machine. Both using 2.5 alpha versions:
* Renamed .mixxx to Mixxx and put it into the C:\Users\...\AppData\Local\Mixxx
* Installed Mixxx
* After start went into preferences to relink. (when clicking on "relink" simply nothing visibly happens).
* closed Mixxx
* restarted Mixxx (and retried to relink also)

![Screenshot 2024-02-02 211814](https://github.com/mixxxdj/mixxx/assets/622460/fbf49abb-2790-4037-86ad-f7907b230eb5)

Maybe I have accidentally touched the recording button or mixx just created the recording directory using the linux file structure:
![Screenshot 2024-02-02 212703](https://github.com/mixxxdj/mixxx/assets/622460/663cc156-8901-4edf-9d89-ca4aef44ca8b)

also visible here after relinking and a restart of mixxx the old path is still there. Interestingly C:\ is always only shown on file which are currently selected.
![Screenshot 2024-02-02 214946](https://github.com/mixxxdj/mixxx/assets/622460/1afe01df-3c1d-4262-9662-777f552c7224)

### Version

2.5-alpha-222-gae53865a26 (main)

### OS

Linux, Windows

**Comment by ronso0** [comment] 2024-02-02 22:08
Do you still have the log file from the first session on Windows when you did the relink?
(Mixxx stores 11 log files, mixxx.log.10 is the oldest)

If no, can you go back to square one (remove/rename the Mixxx config directory in Windows) and relink again?
Then please share the log file. Maybe it contains some hints.

Actually the relinking should have been fixed with #12462 but I'm pretty sure no one tested this cross-OS.

**Comment by ronso0** [comment] 2024-02-02 22:17
Additionally, (again: simulate a fresh install by removing the Mixxx config directory) could you add one dummy music directory with just some tracks, then move it and try to relink?

**Comment by CaMeLCaseError** [comment] 2024-02-02 23:11
i will just do it again and save the logs... didn't know they existed until now. and still don't know where...
 
so I'll:
* rename the Mixxx folder to Mixxx_bak
* extract the .mixxx folder from Linux 
* rename .mixxx to Mixxx
* start Mixxx 2.5

where do I find the logs? I can also start Mixxx with --developer if that gives some more output.

`could you add one dummy music directory with just some tracks, then move it and try to relink?`
You mean to create one dummy on linux and do the whole process? or just testing if relinking generally works on windows?

**Comment by CaMeLCaseError** [comment] 2024-02-02 23:34
I made a fresh mixxx config directory on linux and repeated the process.

started mixxx from command line:
![Screenshot 2024-02-03 002904](https://github.com/mixxxdj/mixxx/assets/622460/08ec14c3-b551-422b-8cb4-68b4090389b0)

log is here
[mixxx.log](https://github.com/mixxxdj/mixxx/files/14146479/mixxx.log)

**Comment by CaMeLCaseError** [comment] 2024-02-02 23:43
only windows
* started Mixxx without any Mixxx folder
* added some album
* closed mixxx
* moved the album
* started mixxx
* relinked. 
 
screenshot and logs attached :)
![Screenshot 2024-02-03 003948](https://github.com/mixxxdj/mixxx/assets/622460/d7243f40-7e62-4c76-844a-08989c57e182)
[mixxx.log](https://github.com/mixxxdj/mixxx/files/14146637/mixxx.log)

**Comment by CaMeLCaseError** [comment] 2024-02-02 23:45
[mixxx.log.1.log](https://github.com/mixxxdj/mixxx/files/14146651/mixxx.log.1.log)

**Comment by ronso0** [comment] 2024-02-26 19:52
Okay, so the issue is that the Linux paths stored in the database are prefixed with c:\ for some reason.
`/home/user/music`
becomes
`C:/home/user/music` (note the forward slashes)
which is obviously not found in the _track_locations_ table.

I'll take a look...

**Comment by ronso0** [comment] 2024-08-06 20:47
Fixed in 2.4 by #12878

**Closed by ronso0** 2024-08-06 20:47 UTC
Labels: library, bug
