### ISSUE TITLE
Wishlist: Add syntax for an "OR" search operator

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#12059] opened 2023-10-04 21:51 UTC
### Feature Description

As mentioned in [the manual](https://manual.mixxx.org/2.4/en/chapters/library#using-search-operators):

> You can combine operators but there’s no way to do an “OR” search right now.

It would be pretty useful to have the ability to combine search queries disjunctively, e.g. for fuzzy searches over multiple genres/crates/etc. The primary question would be what the search operator should be, e.g. `|` or `;` (I'd go with a symbol over a plain `OR` to avoid confusion when searching for a track containing the string `OR`).

**Comment by ronso0** [comment] 2023-10-04 21:57
Duplicate of https://github.com/mixxxdj/mixxx/issues/8881

Feel free to reopen in case I overlooked a detail.

**Closed by ronso0** 2023-10-04 21:57 UTC
Labels: feature
