### ISSUE TITLE
Split screen for folder views and playlists

### ISSUE THREAD

**Issue by AlrightHector** [mixxxdj/mixxx#12831] opened 2024-02-17 12:00 UTC
### Feature Description

I'd like to see a split screen on the right so when using AutoDJ you can view the current playlist while browsing folders for tracks. Then, if possible tracks could then be dragged into the current playlist.

**Comment by ronso0** [comment] 2024-02-17 13:38
This is a dupe of #6375, and #12752 
If you have more details to add, please do so in #6375 
Thank you!

**Closed by ronso0** 2024-02-17 13:38 UTC
Labels: feature

**Comment by Eve00000** [comment] 2025-02-16 11:48
I'd like to invite you to take a look at PR https://github.com/mixxxdj/mixxx/pull/14350 Preparation Window + Preparation Lists.
With a second window in library it's possible to D&D tracks from Playlists & Crates to Auto DJ / .Playlists & Crates (and preparation lists)
All loaded tracks to any player are automatically saved in 'today's Preparation List", you can also add last second ideas. The preparation list can stay opened in the second library window above the standard library view containg the siidebar and the known library view.
I'm keen on feedback.

**Comment by AlrightHector** [comment] 2025-02-17 09:25
This looks to be exactly what I was requesting. Is there a way I can install this or do I need to wait for it to be included in a future update?

**Comment by AlrightHector** [comment] 2025-02-18 09:52
magic, thanks

*> **Λ **v **<*

**Comment by AlrightHector** [comment] 2025-03-23 09:25
This is pretty close to what I'm looking for. I'd like to see the Auto DJ
list in the top section and the lower window be able to browse the other
folders. I'd also like to see it rolled out to the Tango theme if possible.

*> **Λ **v **<*

**Comment by Eve00000** [comment] 2025-03-23 12:12
all your wishes are already in this pr:

![Image](https://github.com/user-attachments/assets/857a37fd-4e54-4a64-9a73-eb3120277166)

**Comment by AlrightHector** [comment] 2025-03-23 16:09
I'm not seeing the preview library window in the Tango Skin. It's also  not appearing as an option in the settings (as it does in the  LateNite skin). Im using the MAC ARM on a MacBook Air M3.

![Image](https://github.com/user-attachments/assets/33851908-6a10-4a7a-b3e4-0f2f061f91bb)

**Comment by Eve00000** [comment] 2025-03-23 16:54
I added the other skins with the [commit on 2025/03/04](https://github.com/mixxxdj/mixxx/pull/14350/commits/f598657a05626d509c6b2d8e860e2712ad8333c7) so you need to use a build after that date.
I see now CI did not execute the building process for the artifacts. I'll try to start it now.

**Comment by AlrightHector** [comment] 2025-03-23 17:14
Thanks, I'm not a programmer so struggling to find my way around GtHub. Can
you provide a link for the build when it's ready?
Thanks for your work on this.

*> **Λ **v **<*

**Comment by Eve00000** [comment] 2025-03-24 20:16
@AlrightHector ,
You can find the latest preparation-window-builds in the PR #14350 -> checks -> choose builds -> [scroll to end of page ](https://github.com/mixxxdj/mixxx/actions/runs/14033005184).
Maybe you shoul try to build Mixxx yourself then you could test all features that are not yet in official builds.
more info in [this Mixxx-Wiki-Article](https://github.com/mixxxdj/mixxx/wiki#compile-mixxx-from-source-code)

**Comment by Eve00000** [comment] 2025-03-26 06:43
> the names of the buttons are overlaying the icons. 

I know, it 's in all skins, that's still something to work on.
Enjoy it.
