### ISSUE TITLE
In the spinnies the Vinylcontrol signal is not properly masked

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12202] opened 2023-10-21 10:29 UTC
In the spinnies the Vinylcontrol signal is also visible outside of the round area:

https://github.com/mixxxdj/mixxx/assets/64457745/f7a308f9-c952-41e5-a869-a45cd5894365

Maybe it's just me, but I expected this to be masked as the Cover-Art.

_Originally posted by @JoergAtGithub in https://github.com/mixxxdj/mixxx/issues/12100#issuecomment-1773417550_

**Comment by ronso0** [comment] 2023-10-21 11:28
If it was masked the signal would be clipped, i.e. information be hidden. Is it really desirable to constrain the signal just for keeping the corners clean?
IIUC only clipping is applicable (changing the stack order), not scaling if the graph (when? always? set scale factor based on the assumption that the mask is circular?)l

**Comment by m0dB** [comment] 2023-10-22 00:35
I agree with @ronso0 . The information _is_ part of the vinyl quality image. The fact that we draw it together with the spinny is coincidental. I propose to close this as not a bug.

**Closed** 2023-10-22 08:10 UTC
Labels: minor bug, vinylcontrol
