### ISSUE TITLE
Incredibly high CPU usage on macOS Catalina + Big Sur 

### ISSUE THREAD

**Issue by faithvoid** [mixxxdj/mixxx#11450] opened 2023-04-07 03:51 UTC
### Bug Description

Hi everyone, hope you're all well.

I recently picked up a 2013 Macbook Air (A1466, i7-4650U CPU + Intel HD 5000 GPU + 8GB DDR3 RAM + a 256GB SSD) and, weirdly enough, despite it having slightly better specs than my old Linux laptop (a Thinkpad X220T with an i5-2520M CPU + HD 3000 GPU, 12GB of DDR3 RAM + 256GB SSD), Mixxx runs significantly worse on it and the awful performance can be replicated in both macOS Catalina and Big Sur. 

There's a noticeably delay of a second or two when clicking anything on-screen when playback is occuring, occasionally the software won't register the play/pause buttons on my controller (a Hercules DJ 4Set), the waveform gets INCREDIBLY choppy, and the CPU immediately gets maxed out to over 100% with the GPU hovering around 6%. Audio playback seems to be fine though despite all the visual performance issues. The issue can be replicated across all skins and waveform type settings so it doesn't appear to be the issue of any one skin or waveform engine. This behaviour doesn't show up in any other DJ software on this system. 

I've noted 2 different things that have alleviated the issue somewhat, although none of them are an ideal solution as it removes a lot of ideal functions.

1) Alt-Tabbing seems to drop the CPU usage from 120+% to 20% for some reason. This of course is the nuclear option, as not seeing what you're DJing is impractical. 

2) Disabling spinnies + waveforms seems to drop it down to about 40%, which is a lot better, but of course you're limited in what you can do as a DJ without a waveform except for beatmatching by ear. 

I'm at a loss as to how to proceed from here, let me know if there's any additional information I can attach, or steps I can attempt to take to alleviate these issues. The issues also appear using the latest development snapshot of 2.4. 

### Version

2.3.4

### OS

macos Big Sur, macOS Catalina

**Comment by JoergAtGithub** [comment] 2023-04-07 09:35
I fear there is no easy fix. Could you try the latest build https://github.com/mixxxdj/mixxx/actions/runs/4461907396?pr=10989 from PR #10989 and report back, if this solves your issue?
Does the issue also occur with Mixxx 2.3.3?

**Comment by faithvoid** [comment] 2023-04-07 22:04
> 

Hi there Joerg, thank you so much for getting back to me! With the PR build you linked, UI performance is way more responsive, maxing out at about 73% CPU usage & 12% GPU usage with two decks playing (and around 86% with 4 decks playing) with the waveforms set to 60FPS & latency at 10ms! The only persisting issue is the occasional missed MIDI input, but that might just be something on my end as this controller is a decade old, I'll do some comparing to my Mixxx on my Ubuntu Studio partition + tests with my other controller and see what's up there. 

I tried rolling back to 2.3.3 and the issue seems to persist there too. Not too sure where it was introduced, as I remember Mixxx working flawlessly on my old Hackintosh machine 2 years ago.

**Comment by JoergAtGithub** [comment] 2023-04-07 22:09
Thanks for testing. Until now only users on th 2.4 branch were affected, this is the first report for the 2.3 release I read.

**Comment by cgodinez1271** [comment] 2023-04-15 21:07
Poor system performance may be due to CPU/GPU throttling caused by high temperatures resulting from heavy CPU/GPU usage. Install an app like TGPro to monitor the system temperature and ensure that the fans are functioning properly. TGPro also provides the option to set rules to boost the fan speed as needed, which can help to prevent throttling and improve system performance.

Another suggestion to improve the system's cooling is to clean the fan subsystem of your MP. Over time, dust can accumulate in the fan subsystem, leading to reduced airflow and increased temperature. If you feel comfortable doing so, opening up your MP and cleaning the fan subsystem can help improve airflow and reduce the risk of overheating. However, it is important to follow proper procedures and precautions when opening up and cleaning the computer to avoid causing damage.

**Comment by JoergAtGithub** [comment] 2023-05-29 10:33
Fixed by #10989

**Closed by JoergAtGithub** 2023-05-29 10:33 UTC
Labels: bug, performance, macos
