### ISSUE TITLE
MIDI for light only sends on crossfader movement

### ISSUE THREAD

**Issue by DerScherenmann** [mixxxdj/mixxx#11612] opened 2023-05-30 15:25 UTC
### Bug Description

With MIDI for light enabled in mixxx, mixxx only transmits notes (MIDI signal) when the crossfader is moved over the middle position. Otherwise no notes are transmitted. Deck changes with volume meters after the crossfader was in the middle for 3 seconds are also not recognized and transmitted.

MIDI dump with `amidi -p hw:0,0 -d`

```
903066
  3000
803000

903067
  3000
803000

903066
  3000
803000

903067
  3000
803000
```
(Crossfader was moved 4 times over the middle position)

Output is a Virtual midi port created with `sudo modprobe snd_virmidi midi_devs=1`

### Version

Mixxx 2.5.0-alpha

### OS

Arch Linux 6.3.1-arch1-1

**Comment by DerScherenmann** [comment] 2023-06-05 10:57
Mixxx version mixxx-2.3.5-1 works for me

**Comment by daschuer** [comment] 2023-09-13 11:21
@JoergAtGithub Do you have an idea what cause this regression. 

@DerScherenmann Can you confirm that the issue also happen with the latest Mixxx 2.4-beta? 

If this is the case a 'git bisect' run would be super helpful from the 2.4 branch. 
Are you able to do it?

**Comment by Swiftb0y** [comment] 2023-09-13 11:47
The issue fixed in #11953 might related to this...

**Comment by geraldog** [comment] 2023-09-30 22:25
This is by design, see the 2013 message from the author in the boards: https://mixxx.discourse.group/t/midi-output-for-lightcontrol/13224/2

**Comment by daschuer** [comment] 2023-10-18 12:51
OK, so this can be closed. Please reopen if you disagree.

**Closed by daschuer** 2023-10-18 12:51 UTC
Labels: regression, bug
