### ISSUE TITLE
Filter Folder - saved search queries

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#13722] opened 2024-10-06 16:41 UTC
### Feature Description

I wrote it some years ago....what i really miss since switching from VDJ to Mixxx are the filter folders:

The filter folders are only saved search queries (the blue ones in the screenshot). If Mixxx gets a new feature that works like the playlist feature, that whould be the first step an helped me a lot to create about 50-100 filters with the search query parameters. 
Every entry is a search query with a title. 

In the contect menu of Mixxx is there still feature (searching the same path, same genre etc)

![VDJ-Filter-Folder](https://github.com/user-attachments/assets/723d6315-8266-486c-8295-7530f2985c59)

**Comment by ronso0** [comment] 2024-10-06 18:15
Virtual DJ's "Filter Folder" = Smart Crates
https://www.virtualdj.com/manuals/virtualdj/interface/database/smartfolders/index.html#filter
That page explains the "Folder" types in VDJ:
* List Folders: PLaylists in Mixxx
* Filter Folders: Smart Crates
* Favorite Folders: Quick Links in Mixxx' Computer feature

So this is again a duplicate of #5575, therefore I'll close it now.
I don't consider it helpful posting the same request again, especially after my latest response in #10767

**Closed by ronso0** 2024-10-06 18:15 UTC
Labels: feature
