### ISSUE TITLE
EQ knobs in LateNight PaleMoon look different with Qt6.5.3

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12972] opened 2024-03-16 20:32 UTC
### Bug Description

In Qt6 builds, an additional light grey circle appears on the bigger mixer knobs, but not on the effect knobs.

Knobs in Mixxx 2.4 (Qt5):
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/0dd6bd72-33b8-47c6-a619-665021ad4b51)

Knobs in Main (Qt6.5.3):
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/a78a0919-02c7-471b-8883-1c6dedf0b44e)

### Version

Main

### OS

Windows 11

**Comment by ronso0** [comment] 2024-03-16 23:57
I can not confirm this with Qt 6.2.3 Knobs look indentical.
Which Qt version do you use?

However, the template looks different than the rendering.
Might very well be that the current rendering is the result of a Qt bug which was fixed in your version, and now it is rendered correctly.
![image](https://github.com/mixxxdj/mixxx/assets/5934199/cfcaaf58-ac27-4916-afb7-e91fba93d83c)

**Comment by JoergAtGithub** [comment] 2024-03-17 00:23
I use Qt6.5.3 from our VCPKG buildenv.

**Comment by acolombier** [comment] 2024-05-14 11:51
What would be the suggested fix here? Change the SVG so it keeps the "rendering bug" on newer Qt version or change it so it looks like expected on older Qt version?

**Comment by acolombier** [comment] 2024-05-14 12:53
I just had a play and it looks like the rendering bug is caused by the `linearGradient` referencing the other `linearGradient`, due to the multiple transform. Seems like the side effect is that it changes the z-index and render above the the black and grey stroking. If you remove the gradient and use a flat colour, this is the closer option I could get

![image](https://github.com/mixxxdj/mixxx/assets/7086688/5e017a1f-bfcb-40aa-a74c-87e750289cf1)

**Comment by acolombier** [comment] 2024-05-14 14:58
I've changed my skin setting to have the super knob as well and remove the main mixer which was shifting component. I've used @JoergAtGithub's visual to compare the two looks. Besides fonts and colour tone (likely due to screen colour correction), I think this looks pretty good? 

https://github.com/mixxxdj/mixxx/assets/7086688/36e4899f-f2c6-4d66-bc70-fd4799c7afa8

**Comment by acolombier** [comment] 2024-05-24 12:29
@ronso0 do you think the above is a good enough fix? Should I create a PR for it?

**Comment by ronso0** [comment] 2024-05-24 12:57
In the gif you posted the EQ knobs look exactly as in the Qt6.5.3 screen @JoergAtGithub posted in the description.
Am I missing something?

**Comment by acolombier** [comment] 2024-05-24 13:00
Yes, this is a fade between Qt6.2.4 with my fix and @JoergAtGithub 's screenshot

**Comment by ronso0** [comment] 2024-05-24 13:04
Sorry, I don't see a relevant difference. The ring is still there with const color, no gradient / fading to bg color top->bottom.

**Comment by ronso0** [comment] 2024-05-24 13:05
I can try to scale the small knobs up and share that, but I can't test since I'm still on Qt 6.2.3 (where knobs look like they do with Qt5).

**Comment by acolombier** [comment] 2024-05-24 13:06
I'm confused now, I though the look on Qt 6.5.3 was the one we wanted to keep, is that the other way around?

**Comment by Swiftb0y** [comment] 2024-05-24 13:45
No, we wanted to keep the consistent Qt5 look (the one where it looks like the button are being lit from above and throwing a shadow below).

**Comment by ronso0** [comment] 2024-05-24 13:51
Yep :smile: we want to keep the skeumorphic look from 2.4, with the gradients, soft edges etc.

So, since the small knobs (fx Meta knobs) still look as desired, I assume something in the big knob's SVG is broken/incompatible/Qt quirk fixed/new Qt bug that prevents the soft rendering from Qt 6.2.3 and earlier.

That's why I suggested to clone the small knobs and carefully scale the elements up (maybe shift/resize/reposition the gradients) to get the old look. (this assumes the knobs look as desired in the respective SVG editor, which they do for me in Inkscape 1.3.2 on Linux)

**Comment by JoergAtGithub** [comment] 2024-12-15 14:43
@ronso0 I guess a fix for 2.5.0 is too risky?

**Comment by ronso0** [comment] 2024-12-15 14:57
I'll try upscaling the intact effect parameter knob today and provide a commit for testing.

Testing should be straight forward, I don't see a risk. Would be really good shipping 2.5.0 with a nice GUI, this simply slipped off my TODO list.

**Comment by ronso0** [comment] 2024-12-15 19:11
@JoergAtGithub could you please post a screenshot of the knobs in the Main/Headphone mixer?

I tried upscaling the fx knob but more tweaking is required to get the Qt5 look.
If the Main knobs look okayish I could work off those.

**Comment by JoergAtGithub** [comment] 2024-12-15 23:19
Latest Mixxx 2.5 Qt6.5 100% system scaling:
![grafik](https://github.com/user-attachments/assets/ebe6a31f-ae9f-4f84-a56c-17b57c39aa9f)

Latest Mixxx 2.5 Qt6.5 150% system scaling (Windows default for my screen):
![grafik](https://github.com/user-attachments/assets/347ce118-e03e-4fe8-b239-f7817bc0fc5c)

Latest Mixxx 2.5 Qt6.5 200% system scaling:
![grafik](https://github.com/user-attachments/assets/8313da0b-ca3c-46c3-a006-3458f71a5d55)

Mixxx 2.4.2 Qt5.15 100% system scaling:
![grafik](https://github.com/user-attachments/assets/01b00b4a-9dd4-44d4-81f4-048511d9c083)

Mixxx 2.4.2 Qt5.15 150% system scaling:
![grafik](https://github.com/user-attachments/assets/7b1b30ec-d384-47e5-acdb-c73426084a0d)

Mixxx 2.4.2 Qt5.15 200% system scaling:
![grafik](https://github.com/user-attachments/assets/0c7c73b5-a5e2-44e6-aad3-011bd3b8abe3)

**Comment by ronso0** [comment] 2024-12-16 00:21
Okay, thank you!
So the smaller Main and effect Meta/Super knobs are still rendered as desired.

I'll try again.

**Comment by ronso0** [comment] 2024-12-18 01:17
@JoergAtGithub did you notice that all knobs are blurred, like being rendered at 100% then being upscaled?
For me, with Qt 6.2.3 everything¹ looks crisp @200%
(and IIRC it also did with Qt5.12.8)
![image](https://github.com/user-attachments/assets/70fb2360-22e0-441b-bdbc-a366b8eca9b3)
¹except the effect flow indicators (chevrons)

**Comment by ronso0** [comment] 2024-12-18 01:23
I start to belive that in your version (6.5 on Windows) the issue is simply that the top (diagonal) gradient with the blur filter is not rendered. Maybe that can be replaced with a ring or whatever.

I'll try to fix this tomorrow or the day after, but it's hard since I don't see the bug. All I can do is try to get the sme look without blur filter and translucent gradient.

Should be _(one of)_ the last 2.5 bugfixes.

**Comment by ronso0** [comment] 2024-12-18 09:13
@JoergAtGithub could you please check if this change fixes the appearance (at least the blurry knobs):
https://github.com/mixxxdj/mixxx/blob/2.5/res/skins/LateNight/palemoon/knobs/knob_bg_regular.svg?short_path=e944cb4#L6-L7
change this
```
   height="34"
   width="40">
```
to
```
   height="68"
   width="80"
   viewBox="0 0 40 34">
```

**Closed** 2024-12-20 09:06 UTC
Labels: ui, minor bug
