### ISSUE TITLE
Pioneer FLX-4 crossfader inverted (hamster style)

### ISSUE THREAD

**Issue by Kris-Dorey** [mixxxdj/mixxx#12622] opened 2024-01-22 11:54 UTC
### Bug Description

Hi there I have a FLX-4 controller with the latest firmware and when it’s connected to mixxx the crossfader is inverted (hamster style) now I have tried going into preferences crossfader (hamster style) witch made zero difference at all i am also use the current FLX-4 controller mapping, yet the controller works just fine with serato and rekordbox

any help would be greatly appreciated as I’m now at my wits end

### Version

2.3.6

### OS

Windows 11

**Comment by Swiftb0y** [comment] 2024-01-22 12:37
it should work. have you made sure to apply the preferences correctly? If so, please start mixxx from the commandline with the `--controllerDebug` flag. then move the crossfader from left to right once! and post the commandline output produced while moving the fader here. Thank you.

**Comment by Kris-Dorey** [comment] 2024-01-22 12:44
@Swiftb0y  i can tell u now it does not work and the preferences are applied correctly, and none of the above works this has also been tested on 3 different laptops with same results ..... 

even a friend that uses Mixxx as taken a look and can not work this out and also tried it on her laptop with the same problem

**Comment by Swiftb0y** [comment] 2024-01-22 13:23
That sounds like a problem with the mapping (unlikely from what I can tell right now) or your hardware.

> also im on windows so --controllerDebug from command line DOSE not work !

I'm not on windows but I'm pretty sure you can start mixxx from the commandline and the flag should work (am I wrong @JoergAtGithub?). Just open the path where mixxx is installed in `cmd` and then execute `mixxx.exe --controllerDebug`. 


Anyways, if that still doesn't work, you can try a third party programm like `midi-ox` to take a look at the midi messages sent by the controller. They should be `0x6B 0x1F` and `0x6B 0x3F` and if you move the crossfader from left to right, the values for the `0x1F` control should be ascending. 

Also, please post a copy of your mixxx.cfg file. It should be in the [same directory as your mixxx.log file](https://github.com/mixxxdj/mixxx/wiki/Finding%20the%20Mixxx.log%20file#windows)

**Comment by Kris-Dorey** [comment] 2024-01-22 13:27
@Swiftb0y yes this is also what im now thinking that its the mapping but since the FLX 4 is pretty new there is only 1 mappings that i can find for it in the Mixxx forums 

PS will post the mixxx.cfg when i get home this evening

**Comment by Swiftb0y** [comment] 2024-01-22 13:37
Ah, I overlooked that fact. Can you link me the exact forum post? That mapping is probably buggy. If you instead use mixxx 2.4 (don't worry its pretty stable) you will find a mapping for the FLX4 built-in (make sure you remove the forum mapping first) which has not received any complaints so far.

**Comment by Kris-Dorey** [comment] 2024-01-22 13:40
@Swiftb0y here is the forum post for the mapping 

https://mixxx.discourse.group/t/pioneer-ddj-flx4/26553

Mixx 2.4 has the same issues so can't even use that

**Comment by Swiftb0y** [comment] 2024-01-22 13:52
Good to know thank. Then in that case I'd need to see the midi messages. 
I must also ask you to mind your tone. I'm not willing to assist you further if your responses remain this aggressive. Thank you.

**Comment by Kris-Dorey** [comment] 2024-01-22 13:55
@Swiftb0y I'm sorry I'm not being aggressive and if I come across that way I apologise it's not my intention

**Comment by Swiftb0y** [comment] 2024-01-22 13:55
As a quick workaround you can try adding `<inverted/>` tags to the `<options>` in the xml that belong to the two `<key>crossfader</key>` `<control>`s. Not sue how reliable that is.

**Comment by Swiftb0y** [comment] 2024-01-22 14:00
then I recommend you to look at the wiki page that will introduce you to the structure of a basic midi mapping: [https://github.com/mixxxdj/mixxx/wiki/MIDI controller mapping file format](https://github.com/mixxxdj/mixxx/wiki/MIDI%20controller%20mapping%20file%20format)

**Comment by Kris-Dorey** [comment] 2024-01-22 14:01
Will do thank you for your help so far buddy

**Comment by ronso0** [comment] 2024-01-22 14:46
> As a quick workaround you can try adding `<inverted/>` tags to the `<options>` in the xml that belong to the two `<key>crossfader</key>` `<control>`s. Not sure how reliable that is.

You need to go to Preferences -> Controllers -> FLX4
The click on the FLX4-...xml file link to open that file in a text editor.
Find the two controls for "crossafder" and add `<Invert/>` into the options nodes, right below each `<fourteen-bit...>` node.
https://github.com/mixxxdj/mixxx/blob/7ab184441dfe51eec7455bf7be86d4f4f6dab880/res/controllers/Pioneer-DDJ-FLX4.midi.xml#L624-L643

If that file is write-protected on Windows, yo need to both the FLX xml and js files  to your <user-settings-directory>/controllers first, the edit.
https://manual.mixxx.org/2.4/en/chapters/appendix/settings_directory.html

**Comment by Kris-Dorey** [comment] 2024-01-22 17:08
Hi @ronso0 i tried what u said with the <Invert/> in the FLX4-...xml still the same issue here is a copy of the .xml code for the crossfader

![Screenshot_1](https://github.com/mixxxdj/mixxx/assets/90153029/ab0e4190-f68f-4046-8918-0e0bcddd7844)

**Comment by Kris-Dorey** [comment] 2024-01-22 17:46
Hi @Swiftb0y i have also tried  mixxx 2.4 as u recommended as it has the FLX-4 mappings built in and the issue is the same, i am now very confused as to what is going on

**Comment by Swiftb0y** [comment] 2024-01-22 17:54
Yes me too. The only way forward of debugging this is to get a look into what the controller is actually doing, which is why I asked for the midi info produced by `--controllerDebug` or midi-ox.

**Comment by Kris-Dorey** [comment] 2024-01-22 18:29
@Swiftb0y  here is what midi-ox sent back i after moving the crossfader i don't know what im looking for myself

   
[MIDILog.txt](https://github.com/mixxxdj/mixxx/files/14014079/MIDILog.txt)

**Comment by Swiftb0y** [comment] 2024-01-22 20:14
So its not emidiatly apparent from the log, did you move the crossfader left-right-left or right-left-right?

**Comment by Swiftb0y** [comment] 2024-01-22 20:15
whats your crossfader reversal setting in rekordbox?

**Comment by Kris-Dorey** [comment] 2024-01-22 20:23
@Swiftb0y rekordbox works fine 
![Screenshot_2](https://github.com/mixxxdj/mixxx/assets/90153029/271d8c22-c99f-4e63-a67e-23148520ead4)

**Comment by Kris-Dorey** [comment] 2024-01-22 20:25
> So its not immediately apparent from the log, did you move the crossfader left-right-left or right-left-right?

yes i did buddy .

**Comment by Swiftb0y** [comment] 2024-01-22 20:26
yes, but which of one those...

**Comment by Kris-Dorey** [comment] 2024-01-22 20:27
> yes, but which of one those...

sorry both left to right and right to left

**Comment by Swiftb0y** [comment] 2024-01-22 20:33
yes. that is also apparent. My question is what orientation the crossfader was when you started and ended the recording. That is crucial for me to understand whether the controller is sending signals inverted or mixxx is interpreting them inverted.

**Comment by Kris-Dorey** [comment] 2024-01-22 20:37
> yes. that is also apparent. My question is what orientation the crossfader was when you started and ended the recording. Did you start with the crossfader on the left or on the right? That is crucial for me to understand whether the controller is sending signals inverted or mixxx is interpreting them inverted.

sorry i be leave i ended with it on the right  but crossfader was in the middle to start so i middle left to right

**Comment by Kris-Dorey** [comment] 2024-01-22 20:39
> yes. that is also apparent. My question is what orientation the crossfader was when you started and ended the recording. Did you start with the crossfader on the left or on the right? That is crucial for me to understand whether the controller is sending signals inverted or mixxx is interpreting them inverted.

im actually starting to think its mixxx as its fine in serato and rekordbox

**Comment by Swiftb0y** [comment] 2024-01-22 20:52
may be the case. But I'm still not sure what the issue is. It could also be the controller and mixxx not accounting for it correctly (still the fault of mixxx, but I need more data to understand where the issue lies exactly).

So with some guesswork it seems the controller is behaving as expected. I'll try to look further into it.

**Comment by Swiftb0y** [comment] 2024-01-22 21:11
No worries I think I found the problem.

**Comment by Kris-Dorey** [comment] 2024-01-22 21:20
> No worries I think I found the problem.

oh what do u think it is buddy

**Comment by Swiftb0y** [comment] 2024-01-22 21:28
nevermind. I misunderstood the feature. So I need more clarification. When you say it is inverted, does that mean that the movement of your crossfader does not match the onscreen movement or does that mean that when the crossfader is on the left the left deck is still muted?

**Comment by Kris-Dorey** [comment] 2024-01-22 21:34
> nevermind. I misunderstood the feature. So I need more clarification. When you say it is inverted, does that mean that the movement of your crossfader does not match the onscreen movement or does that mean that when the crossfader is on the left the left deck is still muted?

yes if the crossfader is say in the middle on my FLX-4 and i slide it to the left deck in Mixxx it will go to the right deck and vice versa if i go from the middle to the right on the FLX-4 it will go to the left in Mixxx

**Comment by Swiftb0y** [comment] 2024-01-22 21:48
okay, that is unrelated to the hamster style preference option. That will only change the output sound, not the visual. What skin are you using? Can you send me another midi-ox log? Preferable one containing just the messages from one slide from the left to the right.

**Comment by Kris-Dorey** [comment] 2024-01-22 21:53
> okay, that is unrelated to the hamster style preference option. That will only change the output sound, not the visual. What skin are you using? Can you send me another midi-ox log? Preferable one containing just the messages from one slide from the left to the right.

Mixxx skin im using is : LateNight PaleMoon,

and here is the midi-ox log from full left to right only 
[MIDILog.txt](https://github.com/mixxxdj/mixxx/files/14015833/MIDILog.txt)

**Comment by Kris-Dorey** [comment] 2024-01-22 21:57
can confirm that its not being affect by the skin i have tried all skins and its still inverted not matter what skin i use

**Comment by Swiftb0y** [comment] 2024-01-22 21:57
Okay thank you. The controller is sending the correct messages. I have no idea right now why this is happening.

**Comment by Kris-Dorey** [comment] 2024-01-22 22:00
> Okay thank you. The controller is sending the correct messages. I have no idea right now why this is happening.

ok i will continue to use rekordbox until we can find a fix for this, but thank u very much for ur help trying to get to the bottom of this

**Comment by Swiftb0y** [comment] 2024-01-22 22:13
Do that then. I'll close this for now. feel free reopen if this comes up again for someone else. I'll try to get a hold of an FLX4 in the meantime.

**Closed by Swiftb0y** 2024-01-22 22:13 UTC
Labels: bug

**Comment by Kris-Dorey** [comment] 2024-01-22 22:18
ok

**Comment by Kris-Dorey** [comment] 2024-01-22 22:24
Please Reopen this as it unsolved

**Comment by grizeldi** [comment] 2024-01-25 18:58
I retested the latest binding I could find in the linked forum thread (from this post https://mixxx.discourse.group/t/pioneer-ddj-flx4/26553/24?u=grizeldi), as the binding is merged only into 2.4 and not into 2.3 branch. The crossfader seems to behave as intended, I can't find anything that would be inverted.

Ubuntu 23.10, 64 bit
Mixxx 2.3.6 (flatpak from flathub)
ALSA audio backend

**Comment by Kris-Dorey** [comment] 2024-01-25 19:06
@grizeldi look at all the above comments there is a bug so i I don't now what your talking about plus I'm on windows not Linux

**Comment by grizeldi** [comment] 2024-01-25 19:36
Next up, Windows 10 test. This time on the 2.4 branch with the official binding, so we can actually know which binding we're talking about. No crossfader issues to be found here either. My deck 1 fader did jiggle a bit up and down in Mixxx when I was cutting with the crossfader, but I'd attribute that to the fader being slightly worn out and moving with the vibrations, not to a software issue.

Windows 10 Home, 64 bit
Mixxx 2.4-beta-394-gd1c0de51b0 from the official website
ASIO audio backend

**Comment by Kris-Dorey** [comment] 2024-01-25 19:39
@grizeldi that's not an option and this was closed because Devs are aware of the issue 

> Okay thank you. The controller is sending the correct messages. I have no idea right now why this is happening.

So learn to please 🤬

**Comment by grizeldi** [comment] 2024-01-25 19:42
@Kris-Dorey I have read through this entire conversation, most of which consist of you giving vague answers which don't help debugging at all in a rather condescending tone. 
Have some patience, we're all working on this in our free time. I am here exclusively because the devs requested someone with a FLX4 to test what is going on in the original FLX4 issue. I'm not here to judge whether there's a bug or not, just to tell the devs that in my testing I couldn't reproduce the issue.

Good luck getting this sorted out, I'm out.

**Comment by Kris-Dorey** [comment] 2024-01-25 19:43
You know what dude just fuck off I've spoken to the developers they're addressing the issue I don't need you help and I don't need your stupid comments just shut the fuck up

**Comment by Kris-Dorey** [comment] 2024-01-25 19:50
Shut up and stop being toxic I've answered as best I can fool 🤤

**Comment by mxmilkiib** [comment] 2024-01-25 19:57
@Kris-Dorey Hey hey now, cross-checking is always worth trying, and it's not uncommon in the world of open source. And I've been utterly sure for days that there had been a bug in software before, and eventually it turns out it was a setting somewhere (this is sometimes known as PEBKAC). No need to get violent with your words, you can always ignore.

**Comment by Swiftb0y** [comment] 2024-01-26 00:27
@grizeldi I'm sorry this escalated like this. Thank you for trying to confirm the issue, I'm sorry you got dragged into this.

**Comment by grizeldi** [comment] 2024-01-26 00:34
It's not your fault, it happens I guess. It'll serve me as a reminder not
to bother with issues where I'm already seeing red flags just by reading
through existing correspondence.

**Comment by Swiftb0y** [comment] 2024-01-26 00:37
Thats a fair takeaway, regardless I still appreciate your comments as without them I would've considered this issue valid and would've wasted more time on it.
