### ISSUE TITLE
Hotcue default color will be ignored

### ISSUE THREAD

**Issue by Russe** [mixxxdj/mixxx#11260] opened 2023-02-08 23:28 UTC
### Bug Description

When setting a hotcue it will always get the yellow/orange color.
I changed the default hotcue color to a different one at Mixxx settings, but this will not solve the issue.
Every time when setting a new hotcue it will get this yellow/orange color.

For testing I removed folder .mixxx with all settings, but this did not solve the issue.
Ass well I tried to remove and install again most recent alpha version, but this did not solve the issue.
As well I tried with different skins, but this did not solve the issue.

### Version

2.4.0-alpha-pre (2.4-alpha-1403... (main))

### OS

Xubuntu 22.04

**Comment by Swiftb0y** [comment] 2023-02-09 00:17
Can you post a screenshot of your Color Preferences?

**Comment by Russe** [comment] 2023-02-09 09:00
As you can see, default color at preferences is green, but when adding a hotcue it will become orange color.

![mixxx-hotcue-colors](https://user-images.githubusercontent.com/1218375/217764837-de4b1569-7cd4-449c-8e8d-d60aafc7d909.png)

**Comment by Swiftb0y** [comment] 2023-02-09 11:35
Confirmed, I can also reproduce the issue on main. I'll try to find some time to investigate.

**Comment by Swiftb0y** [comment] 2023-05-12 19:13
Quick note. I can't reproduce the issue with a fresh settings dir. This is a little more complicated than I thought.

**Comment by Russe** [comment] 2023-05-14 08:16
Currently I'm using this version where I can reproduce the issue: 2.4.0-alpha-pre (2.4-alpha-1403-gcce89d09f3 (main))
It's also reproducible with a new .mixxx folder and new library.

**Comment by Swiftb0y** [comment] 2023-05-14 09:00
Thank you, I'll try my best to find the cause.

**Comment by Swiftb0y** [comment] 2023-05-14 20:46
Ah I see why I couldn't reproduce it anymore. Coloring "By hotcue number" works, but not when choosing some other static color.

**Comment by daschuer** [comment] 2023-05-14 21:57
I have found the issue. It looks like a wrong merge conflict resolve. I will prepare a PR.

**Comment by Swiftb0y** [comment] 2023-05-15 20:39
Fixed in 2.4 newer. @Russe please test these new versions and reopen this issue if it still occurs.

**Closed by Swiftb0y** 2023-05-15 20:39 UTC
Labels: regression, bug, confirmed

**Comment by Russe** [comment] 2023-05-15 20:50
Thanks for fixing this. As I'm on the road during next weeks I can test new versions later.

**Comment by Russe** [comment] 2023-07-23 14:59
Sorry for late answering. I updated to 2.4 beta and hotcue default is fixed now.
Thanks a lot for your work.
