### ISSUE TITLE
[Debian 12] Track Preview don't work

### ISSUE THREAD

**Issue by BrindiWanko** [mixxxdj/mixxx#11660] opened 2023-06-14 12:49 UTC
### Bug Description

Hello,

I have make an fresh install of Debian 12 and Mixxx doesn't work correctly because the track preview don't show:

![bug](https://github.com/mixxxdj/mixxx/assets/129118887/f7491c87-ea6f-4b54-9fec-8da6bddb15f6)

i have make apt update and upgrade and no new update is here.

P.S: The issue is only here when i use Wayland, if i use X11 that's work for information, but i need Wayland for my screen.

Regards

### Version

2.3.3

### OS

Debian 12

**Comment by ronso0** [comment] 2023-06-14 13:15
Please try to reproduce with current stable 2.3.5 from the Mixxx ppa.

Do all waveform types fail?

**Comment by BrindiWanko** [comment] 2023-06-14 16:46
Hello,

I use only the Debian Package for the stability of my systeme.

Regards

**Comment by JoergAtGithub** [comment] 2023-06-14 18:26
Could you try also our latest 2.4 Beta version - it contains a significiant rework of the waveform rendering code.

Was Fedora executed on the same system as Debian?
Which graphic adapter and driver do you use?

**Comment by Swiftb0y** [comment] 2023-06-14 21:52
How did you start mixxx? Waveforms are known to be broken under plain wayland. If you start mixxx from the commandline, you'll need to use `-platform xcb` so Qt will use X11 (which should work since Fedora and Debian are likely running XWayland).

**Comment by Swiftb0y** [comment] 2023-06-15 14:53
adding `-platform xcb` is the semi-permanent fix/workaround. Anything more would likely require developing the mixxx GUI from scratch (which will happen in the future, but not anytime soon). 

Duplicate of #9787

**Closed by Swiftb0y** 2023-06-15 14:53 UTC
Labels: bug

**Comment by JoergAtGithub** [comment] 2023-06-15 17:20
Did anybody test if this still occurs with 2.4 Beta?

**Comment by Swiftb0y** [comment] 2023-06-15 17:30
yes, I did so on accident recently (forgot to add the flag and then had to spend some time debugging). The issue mostly occurs though because the opengl detection logic changed as part of #10989. The result is a rather weird (see opengl status in screenshot), while the gpu waveforms get disabled. I'm not sure if the fact that the waveforms are still broken under wayland with #10989 is a bug or still a technical limitation. @m0dB might know.  
![Screenshot from 2023-06-15 19-27-20](https://github.com/mixxxdj/mixxx/assets/12380386/4f202530-17da-4c06-8db5-08a995e7fdc2)
