### ISSUE TITLE
Analysed track remain in 'to analyse'-crate

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12765] opened 2024-02-09 08:22 UTC
### Bug Description

I still had to analyse songs, in the analyse-crate I selected songs, gave them a color and started analysing them. (only the colored songs).
After analysing them the songs remain in the analyse-crate, all colored songs should disappear but no.
After restat of Mixxxx they stay in the analyse-crate.

### Version

2.5-alpha-229-g7b3e48544a (main)

### OS

Win 10

**Comment by ronso0** [comment] 2024-02-09 09:33
The Analyse view is just a filter for tracks that have been added the last 7 days, and currently Mixxx is not able to decide if the tracks should be (re-)analysed, e.g. when beat detection settings were changed.

Like #10045 this is a dupe of #6521

**Closed by ronso0** 2024-02-09 09:33 UTC
Labels: bug
