### ISSUE TITLE
Add bar and phrase marks to waveform

### ISSUE THREAD

**Issue by JaviVilarroig** [mixxxdj/mixxx#11519] opened 2023-04-29 09:45 UTC
### Feature Description

When I mix two tracks and to make the transition sound better, I always try to align the phrases or ate least the bars in the two tracks.

Right now I have no visual clue in Mixxx wave forms on where are phrases and bars starting. That means that I must be counting beats, bars and phrases to have that information. This is error prone and require extra concentration on my side not to get lost in counting.

I want to have that visual indications available to make my dijing more enjoyable. I will then be able to concentrate on delivering a good sounding mixes to my audience.

**Comment by ronso0** [comment] 2023-04-29 11:22
I'd say this is a duplicate of #10164

Please reopen if you think it's worth tracking this seperately.

**Closed by ronso0** 2023-04-29 11:22 UTC
Labels: feature

**Comment by JaviVilarroig** [comment] 2023-04-29 14:25
I can accept that.

I was unable to fins a related ticket because I was looking for bars and phrases.

FYI. As it's me wanting this feature. I will to try again to have it done by myself. The last try, 3(?) years ago was unsuccessful. So, I will start from scratch.

**Comment by ronso0** [comment] 2023-04-30 13:22
Note there is WIP #4489, so I suggest to not waste time on an alternative implementation but help with that instead (testing & reviewing).

**Comment by JoergAtGithub** [comment] 2023-05-01 22:06
> FYI. As it's me wanting this feature. I will to try again to have it done by myself. The last try, 3(?) years ago was unsuccessful. So, I will start from scratch.

You will not start from scratch, since your last try, @hacksdump and @Holzhaus did a lot of work on the foundation. Have a look at all the merged PRs at: https://github.com/mixxxdj/mixxx/projects/6
Many design decisions are taken and we have a common data model for fixed and flexible beat grid now.
