### ISSUE TITLE
GNOME 44: No drag&drop of tracks from table view to decks and sidebar

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11481] opened 2023-04-15 17:08 UTC
### Bug Description

Shows the prohibit sign.

### OS

Fedora 38 / GNOME 44

**Comment by ronso0** [comment] 2023-04-15 19:02
Are you already looking into this yourself?

If no, which Mixxx version? Are there any clues in the log?

**Comment by uklotzde** [comment] 2023-04-15 19:19
> Are you already looking into this yourself?
> 
> If no, which Mixxx version? Are there any clues in the log?

- I only tested `main` so far.
- No suspicious logs.
- I am not planning to look into it.

**Comment by ronso0** [comment] 2023-04-15 19:29
Are you dragging from a file browser or from within Mixxx? (just in case that makes a difference)
I preume these tracks play fine if you load them from a library feature?

**Comment by uklotzde** [comment] 2023-04-15 19:33
> Are you dragging from a file browser or from within Mixxx? (just in case that makes a difference) I preume these tracks play fine if you load them from a library feature?

Within Mixxx. Drag & drop to the sidebar (e.g. Analysis) also doesn't work.

**Comment by uklotzde** [comment] 2023-04-15 22:06
Works when using Wayland instead of XWayland (`-platform xcb`). But that causes other issues.

**Comment by uklotzde** [comment] 2023-04-15 22:48
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2013235

**Comment by ywwg** [comment] 2023-05-14 20:57
Looks like a fix has been committed and will be released with Mutter 44.2

**Comment by camelpunch** [comment] 2023-06-17 10:07
I can confirm that with latest Mutter, this is resolved.

**Closed** 2023-06-17 10:33 UTC
Labels: bug, confirmed, upstream
