### ISSUE TITLE
Remember the state of the "Large VU meter" setting?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12125] opened 2023-10-16 15:14 UTC
### Feature Description

It resets to the defauly small on restarting the app.

Edit: not related to issue 10122

**Comment by ronso0** [comment] 2023-10-16 15:23
Deere skin I assume, which Mixxx version is it?

#10122 is unrelated (xfader reset was by design)

**Comment by ronso0** [comment] 2023-10-16 15:46
Confirmed.
Reason was the missing 'persist' flag. I pushed the fix directly to 2.4, and merged 2.4 into main (2.5-alpha currently).

**Closed by ronso0** 2023-10-16 15:46 UTC
Labels: feature
