### ISSUE TITLE
Deck waveform loading bug

### ISSUE THREAD

**Issue by atskler** [mixxxdj/mixxx#11344] opened 2023-03-08 13:15 UTC
### Bug Description

If I load track "A" to deck "1" and then I load another "B" track to deck "2" and then I quickly drop the track "A" to deck "2" while it is still loading track "B" it will load and display erroneously the waveform of track "A" - it will be pressed and a silence will be inserted to its end. There also seems to be a rare cases when the waveform is not loaded at all, just a plain line appears.

The issue on video:
https://www.youtube.com/watch?v=LHlp103QXwk

Screenshots:

![fig1](https://user-images.githubusercontent.com/85284199/223722176-3a3e4dda-7835-4099-bcfd-bb2732973be5.png)
![fig2](https://user-images.githubusercontent.com/85284199/223722179-03523eda-6bec-467a-861f-69a02ffb7c9e.png)
![fig3](https://user-images.githubusercontent.com/85284199/223722183-7d5301da-87ab-4bb9-8e6b-bf98f48c0e2a.png)

### Version

2.5.0-alpha

### OS

OpenSUSE Tumbleweed

**Comment by Akashgola123** [comment] 2023-03-09 06:38
I want to work on this issue please assign this issue to me

**Comment by ronso0** [comment] 2023-03-09 18:47
Anyone can try to fix issues, no need to permit or assign that.
1st step would be to reproduce the issue. If you did, try to track it down. As soon as you have a fix for it: just open a pull request to share your progress and get early feedback from devs.

**Comment by daschuer** [comment] 2023-03-09 20:19
Which 2.5-alpha is exactly affected? We have recently fixed a related issue in https://github.com/mixxxdj/mixxx/pull/11333. 
Maybe it is related? 

All this looks like a race condition. The waveform of the new track is probably rendered into the Image sized for the old track.

**Comment by atskler** [comment] 2023-03-09 21:43
2.4-alpha-1419-g0243efdaf8 (main) does it
2.3.4 does it

2.3.3-121-gd1f63374fc works correctly

**Comment by robbert-vdh** [comment] 2023-03-11 12:31
Probably the same thing as this: https://github.com/mixxxdj/mixxx/issues/11280#issuecomment-1455146100

**Comment by MarcPlace** [comment] 2023-03-11 18:28
Yesterday this also has happened a few times to me while DJing, using this commit 6dc6f40e0e9a72672ebbcde8a827545b4b0374c8 (2.4 Branch). Reloading the track again into the deck has mostly fixed it.

**Comment by daschuer** [comment] 2023-03-11 20:27
Can you Identify with which version the issue starts?
We have macOS and windows builds here: https://downloads.mixxx.org/snapshots/2.3/

I have just skimmed through the commits, but did not find something obvious:
These could be candidates to introduce the issue:  
47834bed
cfcd265a

Are you able to do a `git bisect`?

**Comment by MarcPlace** [comment] 2023-03-12 11:20
Trying to track down this issue a bit, so I've reverted commit 47834bedb0983f70429e423f3fb7f97d643fa150 to see if it makes any difference. Unfortunately not, but it takes a bit of effort loading/unloading tracks to get into this state. Could be really something like a race condition:
![01](https://user-images.githubusercontent.com/71196229/224540735-4c76878f-7831-4c5e-829e-67f5031aa270.png)
Also remarkable to see how the Waveforms above differs from the preview waveforms (in this example I've loaded the same track into both decks and went to the same time position):
![02](https://user-images.githubusercontent.com/71196229/224541119-fb3ae322-2795-43c9-aa0f-6bb317a53342.png)
As far as I can tell for now, 47834bedb0983f70429e423f3fb7f97d643fa150 seems not to be the culprit.

**Comment by atskler** [comment] 2023-03-12 13:44
@daschuer I saw that also, probably a variation of the same problem. And maybe this is another variation of it, where one of the decks not draws the waveform at all: https://www.youtube.com/watch?v=5CJmmaRRORc

**Comment by atskler** [comment] 2023-03-12 14:30
> These could be candidates to introduce the issue:
> [47834be](https://github.com/mixxxdj/mixxx/commit/47834bedb0983f70429e423f3fb7f97d643fa150)
> [cfcd265](https://github.com/mixxxdj/mixxx/commit/cfcd265afd0ae70c0f6259b00f8fc5dd4ef38379)

The first committed after v2.3.4 released but the problem already here in v2.3.4 as I mentioned before. So only the second could be a candidate. I'm just building mixxx from before that commit.

**Comment by daschuer** [comment] 2023-03-12 14:35
I have just prepared https://github.com/mixxxdj/mixxx/pull/11359. Please test that as well.

**Comment by atskler** [comment] 2023-03-12 17:34
@daschuer
60727de (2023-02-20 8:56 AM GMT+1) - works correctly
cfcd265 (2023-02-20 9:14 AM GMT+1) - introduces the problems brought up here
5af6037, #11359, daschuer:gh11344 (2023-03-12 4:13 PM GMT+1) - seems to fix all the problems brought up here

**Comment by MarcPlace** [comment] 2023-03-12 22:04
Can confirm that 5af6037d4a602460657864487410707332a3d477 (daschuer:gh11344) has also fixed it for me, at least since this fix I've never managed to get an incomplete preview waveform again. But as I mentioned before, this issue unfortunately happens very rare on my system, so this is just the test result of about 20 minutes of loading/unloading tracks.
I'm already using 2.4 most of the time (because of the Rubberband-r3 feature, which was an incredible step forward in sound quality for Mixxx (btw. thank you guys :). Would be great if you rebase it for 2.4 soon.

**Comment by thomich** [comment] 2023-03-21 06:29
morning

using 2.3.4 and made a video to see what happend, maybe it helps to check the fixed version:
https://watch.screencastify.com/v/9o7hgWWBxIVYca0Dzmx6

thanks for your work

**Comment by daschuer** [comment] 2023-03-21 06:41
This issue is fixed.
You can test this developer snapshot: 
http://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.4-9-geeae59a9f9-win64.msi

**Comment by thomich** [comment] 2023-03-21 07:03
still on linux with mixxx ;)... if there is a developer package for ubuntu 20.04, i will test...

**Comment by daschuer** [comment] 2023-03-21 07:08
Here (You need to be logged in on GitHub): 
https://github.com/mixxxdj/mixxx/suites/11654436323/artifacts/605334095

**Comment by thomich** [comment] 2023-03-21 15:21
thanks @daschuer 

installed, tested and :+1: 
all fine now...

many thanks..

**Closed** 2023-03-21 16:42 UTC
Labels: regression, bug, confirmed

**Comment by thomich** [comment] 2023-03-22 07:50
nay idea, when it will be as update eg. in ubuntu repositories?

**Comment by daschuer** [comment] 2023-03-22 13:24
This will be part of the upcoming 2.3.5. Wich is planned soon. We have not yet scheduled a date.
